--Tab 0
--Tier 0

TCalc_priestUnbreakableWill = {}
TCalc_priestUnbreakableWill.maxPoints = 5;
TCalc_priestUnbreakableWill.talentName = "Unbreakable Will";
TCalc_priestUnbreakableWill.resourceCost = nil;
TCalc_priestUnbreakableWill.castCooldown = nil;
TCalc_priestUnbreakableWill.requirements = nil;
TCalc_priestUnbreakableWill.talentDescriptions = {};
TCalc_priestUnbreakableWill.talentDescriptions[0] = "Increases your chance to resist Stun, Fear, and Silence effects by an additional 3%.";
TCalc_priestUnbreakableWill.talentDescriptions[1] = "Increases your chance to resist Stun, Fear, and Silence effects by an additional 6%.";
TCalc_priestUnbreakableWill.talentDescriptions[2] = "Increases your chance to resist Stun, Fear, and Silence effects by an additional 9%.";
TCalc_priestUnbreakableWill.talentDescriptions[3] = "Increases your chance to resist Stun, Fear, and Silence effects by an additional 12%.";
TCalc_priestUnbreakableWill.talentDescriptions[4] = "Increases your chance to resist Stun, Fear, and Silence effects by an additional 15%.";
TCalc_priestUnbreakableWill.parentTalent = nil;
TCalc_priestUnbreakableWill.childTalent = nil;
TCalc_priestUnbreakableWill.iconPath = "Interface\\Icons\\Spell_magic_magearmor";

TCalc_priestWandSpecialization = {}
TCalc_priestWandSpecialization.maxPoints = 5;
TCalc_priestWandSpecialization.talentName = "Wand Specialization";
TCalc_priestWandSpecialization.resourceCost = nil;
TCalc_priestWandSpecialization.castCooldown = nil;
TCalc_priestWandSpecialization.requirements = nil;
TCalc_priestWandSpecialization.talentDescriptions = {};
TCalc_priestWandSpecialization.talentDescriptions[0] = "Increases your damage with Wands by 5%.";
TCalc_priestWandSpecialization.talentDescriptions[1] = "Increases your damage with Wands by 10%.";
TCalc_priestWandSpecialization.talentDescriptions[2] = "Increases your damage with Wands by 15%.";
TCalc_priestWandSpecialization.talentDescriptions[3] = "Increases your damage with Wands by 20%.";
TCalc_priestWandSpecialization.talentDescriptions[4] = "Increases your damage with Wands by 25%.";
TCalc_priestWandSpecialization.parentTalent = nil;
TCalc_priestWandSpecialization.childTalent = nil;
TCalc_priestWandSpecialization.iconPath = "Interface\\Icons\\Inv_wand_01";

--Tier 1

TCalc_priestSilentResolve = {}
TCalc_priestSilentResolve.maxPoints = 5;
TCalc_priestSilentResolve.talentName = "Silent Resolve";
TCalc_priestSilentResolve.resourceCost = nil;
TCalc_priestSilentResolve.castCooldown = nil;
TCalc_priestSilentResolve.requirements = nil;
TCalc_priestSilentResolve.talentDescriptions = {};
TCalc_priestSilentResolve.talentDescriptions[0] = "Reduces the threat generated by your spells by 4%.";
TCalc_priestSilentResolve.talentDescriptions[1] = "Reduces the threat generated by your spells by 8%.";
TCalc_priestSilentResolve.talentDescriptions[2] = "Reduces the threat generated by your spells by 12%.";
TCalc_priestSilentResolve.talentDescriptions[3] = "Reduces the threat generated by your spells by 16%.";
TCalc_priestSilentResolve.talentDescriptions[4] = "Reduces the threat generated by your spells by 20%.";
TCalc_priestSilentResolve.parentTalent = nil;
TCalc_priestSilentResolve.childTalent = nil;
TCalc_priestSilentResolve.iconPath = "Interface\\Icons\\Spell_nature_manaregentotem";

TCalc_priestImprovedPowerWordFortitude = {}
TCalc_priestImprovedPowerWordFortitude.maxPoints = 2;
TCalc_priestImprovedPowerWordFortitude.talentName = "Improved Power Word: Fortitude";
TCalc_priestImprovedPowerWordFortitude.resourceCost = nil;
TCalc_priestImprovedPowerWordFortitude.castCooldown = nil;
TCalc_priestImprovedPowerWordFortitude.requirements = nil;
TCalc_priestImprovedPowerWordFortitude.talentDescriptions = {};
TCalc_priestImprovedPowerWordFortitude.talentDescriptions[0] = "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%.";
TCalc_priestImprovedPowerWordFortitude.talentDescriptions[1] = "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%.";
TCalc_priestImprovedPowerWordFortitude.parentTalent = nil;
TCalc_priestImprovedPowerWordFortitude.childTalent = nil;
TCalc_priestImprovedPowerWordFortitude.iconPath = "Interface\\Icons\\Spell_holy_wordfortitude";

TCalc_priestImprovedPowerWordShield = {}
TCalc_priestImprovedPowerWordShield.maxPoints = 3;
TCalc_priestImprovedPowerWordShield.talentName = "Improved Power Word: Shield";
TCalc_priestImprovedPowerWordShield.resourceCost = nil;
TCalc_priestImprovedPowerWordShield.castCooldown = nil;
TCalc_priestImprovedPowerWordShield.requirements = nil;
TCalc_priestImprovedPowerWordShield.talentDescriptions = {};
TCalc_priestImprovedPowerWordShield.talentDescriptions[0] = "Increases the damage absorbed by your Power Word: Shield by 5%.";
TCalc_priestImprovedPowerWordShield.talentDescriptions[1] = "Increases the damage absorbed by your Power Word: Shield by 10%.";
TCalc_priestImprovedPowerWordShield.talentDescriptions[2] = "Increases the damage absorbed by your Power Word: Shield by 15%.";
TCalc_priestImprovedPowerWordShield.parentTalent = nil;
TCalc_priestImprovedPowerWordShield.childTalent = nil;
TCalc_priestImprovedPowerWordShield.iconPath = "Interface\\Icons\\Spell_holy_powerwordshield";

TCalc_priestMartyrdom = {}
TCalc_priestMartyrdom.maxPoints = 2;
TCalc_priestMartyrdom.talentName = "Martyrdom";
TCalc_priestMartyrdom.resourceCost = nil;
TCalc_priestMartyrdom.castCooldown = nil;
TCalc_priestMartyrdom.requirements = nil;
TCalc_priestMartyrdom.talentDescriptions = {};
TCalc_priestMartyrdom.talentDescriptions[0] = "Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 10%.";
TCalc_priestMartyrdom.talentDescriptions[1] = "Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 20%.";
TCalc_priestMartyrdom.parentTalent = nil;
TCalc_priestMartyrdom.childTalent = nil;
TCalc_priestMartyrdom.iconPath = "Interface\\Icons\\Spell_nature_tranquility";

--Tier 2

TCalc_priestInnerFocus = {}
TCalc_priestInnerFocus.maxPoints = 1;
TCalc_priestInnerFocus.talentName = "Inner Focus";
TCalc_priestInnerFocus.resourceCost = nil;
TCalc_priestInnerFocus.castCooldown = "Instant\t3 min cooldown";
TCalc_priestInnerFocus.requirements = nil;
TCalc_priestInnerFocus.talentDescriptions = {};
TCalc_priestInnerFocus.talentDescriptions[0] = "When activated, reduces the Mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.";
TCalc_priestInnerFocus.parentTalent = nil;
TCalc_priestInnerFocus.childTalent = nil;
TCalc_priestInnerFocus.iconPath = "Interface\\Icons\\Spell_frost_windwalkon";

TCalc_priestMeditation = {}
TCalc_priestMeditation.maxPoints = 3;
TCalc_priestMeditation.talentName = "Meditation";
TCalc_priestMeditation.resourceCost = nil;
TCalc_priestMeditation.castCooldown = nil;
TCalc_priestMeditation.requirements = nil;
TCalc_priestMeditation.talentDescriptions = {};
TCalc_priestMeditation.talentDescriptions[0] = "Allows 5% of your Mana regeneration to continue while casting.";
TCalc_priestMeditation.talentDescriptions[1] = "Allows 10% of your Mana regeneration to continue while casting.";
TCalc_priestMeditation.talentDescriptions[2] = "Allows 15% of your Mana regeneration to continue while casting.";
TCalc_priestMeditation.parentTalent = nil;
TCalc_priestMeditation.childTalent = TCalc_priestDivineSpirit;
TCalc_priestMeditation.iconPath = "Interface\\Icons\\Spell_nature_sleep";

--Tier 3

TCalc_priestImprovedInnerFire = {}
TCalc_priestImprovedInnerFire.maxPoints = 3;
TCalc_priestImprovedInnerFire.talentName = "Improved Inner Fire";
TCalc_priestImprovedInnerFire.resourceCost = nil;
TCalc_priestImprovedInnerFire.castCooldown = nil;
TCalc_priestImprovedInnerFire.requirements = nil;
TCalc_priestImprovedInnerFire.talentDescriptions = {};
TCalc_priestImprovedInnerFire.talentDescriptions[0] = "Increases the Armor bonus of your Inner Fire spell by 10%.";
TCalc_priestImprovedInnerFire.talentDescriptions[1] = "Increases the Armor bonus of your Inner Fire spell by 20%.";
TCalc_priestImprovedInnerFire.talentDescriptions[2] = "Increases the Armor bonus of your Inner Fire spell by 30%.";
TCalc_priestImprovedInnerFire.parentTalent = nil;
TCalc_priestImprovedInnerFire.childTalent = nil;
TCalc_priestImprovedInnerFire.iconPath = "Interface\\Icons\\Spell_holy_innerfire";

TCalc_priestMentalAgility = {}
TCalc_priestMentalAgility.maxPoints = 5;
TCalc_priestMentalAgility.talentName = "Mental Agility";
TCalc_priestMentalAgility.resourceCost = nil;
TCalc_priestMentalAgility.castCooldown = nil;
TCalc_priestMentalAgility.requirements = nil;
TCalc_priestMentalAgility.talentDescriptions = {};
TCalc_priestMentalAgility.talentDescriptions[0] = "Reduces the mana cost of your instant cast spells by 2%.";
TCalc_priestMentalAgility.talentDescriptions[1] = "Reduces the mana cost of your instant cast spells by 4%.";
TCalc_priestMentalAgility.talentDescriptions[2] = "Reduces the mana cost of your instant cast spells by 6%.";
TCalc_priestMentalAgility.talentDescriptions[3] = "Reduces the mana cost of your instant cast spells by 8%.";
TCalc_priestMentalAgility.talentDescriptions[4] = "Reduces the mana cost of your instant cast spells by 10%.";
TCalc_priestMentalAgility.parentTalent = nil;
TCalc_priestMentalAgility.childTalent = nil;
TCalc_priestMentalAgility.iconPath = "Interface\\Icons\\Ability_hibernation";

TCalc_priestImprovedManaBurn = {}
TCalc_priestImprovedManaBurn.maxPoints = 2;
TCalc_priestImprovedManaBurn.talentName = "Improved Mana Burn";
TCalc_priestImprovedManaBurn.resourceCost = nil;
TCalc_priestImprovedManaBurn.castCooldown = nil;
TCalc_priestImprovedManaBurn.requirements = nil;
TCalc_priestImprovedManaBurn.talentDescriptions = {};
TCalc_priestImprovedManaBurn.talentDescriptions[0] = "Reduces the casting time of your Mana Burn spell by 0.25 secs.";
TCalc_priestImprovedManaBurn.talentDescriptions[1] = "Reduces the casting time of your Mana Burn spell by 0.5 secs.";
TCalc_priestImprovedManaBurn.parentTalent = nil;
TCalc_priestImprovedManaBurn.childTalent = nil;
TCalc_priestImprovedManaBurn.iconPath = "Interface\\Icons\\Spell_shadow_manaburn";

--Tier 4

TCalc_priestMentalStrength = {}
TCalc_priestMentalStrength.maxPoints = 5;
TCalc_priestMentalStrength.talentName = "Mental Strength";
TCalc_priestMentalStrength.resourceCost = nil;
TCalc_priestMentalStrength.castCooldown = nil;
TCalc_priestMentalStrength.requirements = nil;
TCalc_priestMentalStrength.talentDescriptions = {};
TCalc_priestMentalStrength.talentDescriptions[0] = "Increases your maximum Mana by 2%.";
TCalc_priestMentalStrength.talentDescriptions[1] = "Increases your maximum Mana by 4%.";
TCalc_priestMentalStrength.talentDescriptions[2] = "Increases your maximum Mana by 6%.";
TCalc_priestMentalStrength.talentDescriptions[3] = "Increases your maximum Mana by 8%.";
TCalc_priestMentalStrength.talentDescriptions[4] = "Increases your maximum Mana by 10%.";
TCalc_priestMentalStrength.parentTalent = nil;
TCalc_priestMentalStrength.childTalent = TCalc_priestPowerInfusion;
TCalc_priestMentalStrength.iconPath = "Interface\\Icons\\Spell_nature_enchantarmor";

TCalc_priestDivineSpirit = {}
TCalc_priestDivineSpirit.maxPoints = 1;
TCalc_priestDivineSpirit.talentName = "Divine Spirit";
TCalc_priestDivineSpirit.resourceCost = "285 mana\t30 yd range";
TCalc_priestDivineSpirit.castCooldown = "Instant cast";
TCalc_priestDivineSpirit.requirements = nil;
TCalc_priestDivineSpirit.talentDescriptions = {};
TCalc_priestDivineSpirit.talentDescriptions[0] = "Holy power infuses the target, increasing their Spirit by 17 for 30 min.";
TCalc_priestDivineSpirit.parentTalent = TCalc_priestMeditation;
TCalc_priestDivineSpirit.childTalent = nil;
TCalc_priestDivineSpirit.iconPath = "Interface\\Icons\\Spell_holy_divinespirit";

--Tier 5

TCalc_priestForceOfWill = {}
TCalc_priestForceOfWill.maxPoints = 5;
TCalc_priestForceOfWill.talentName = "Force of Will";
TCalc_priestForceOfWill.resourceCost = nil;
TCalc_priestForceOfWill.castCooldown = nil;
TCalc_priestForceOfWill.requirements = nil;
TCalc_priestForceOfWill.talentDescriptions = {};
TCalc_priestForceOfWill.talentDescriptions[0] = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 1%.";
TCalc_priestForceOfWill.talentDescriptions[1] = "Increases your spell damage by 2% and the critical strike chance of your offensive spells by 2%.";
TCalc_priestForceOfWill.talentDescriptions[2] = "Increases your spell damage by 3% and the critical strike chance of your offensive spells by 3%.";
TCalc_priestForceOfWill.talentDescriptions[3] = "Increases your spell damage by 4% and the critical strike chance of your offensive spells by 4%.";
TCalc_priestForceOfWill.talentDescriptions[4] = "Increases your spell damage by 5% and the critical strike chance of your offensive spells by 5%.";
TCalc_priestForceOfWill.parentTalent = nil;
TCalc_priestForceOfWill.childTalent = nil;
TCalc_priestForceOfWill.iconPath = "Interface\\Icons\\Spell_nature_slowingtotem";

--Tier 6

TCalc_priestPowerInfusion = {}
TCalc_priestPowerInfusion.maxPoints = 1;
TCalc_priestPowerInfusion.talentName = "Power Infusion";
TCalc_priestPowerInfusion.resourceCost = "20% of base mana\t30 yd range";
TCalc_priestPowerInfusion.castCooldown = "Instant cast\t3 min cooldown";
TCalc_priestPowerInfusion.requirements = nil;
TCalc_priestPowerInfusion.talentDescriptions = {};
TCalc_priestPowerInfusion.talentDescriptions[0] = "Infuses the target with power, increasing their spell damage and healing by 20%. Lasts 15 sec.";
TCalc_priestPowerInfusion.parentTalent = TCalc_priestMentalStrength;
TCalc_priestPowerInfusion.childTalent = nil;
TCalc_priestPowerInfusion.iconPath = "Interface\\Icons\\Spell_holy_powerinfusion";

--Tab 1
--Tier 0

TCalc_priestHealingFocus = {}
TCalc_priestHealingFocus.maxPoints = 2;
TCalc_priestHealingFocus.talentName = "Healing Focus";
TCalc_priestHealingFocus.resourceCost = nil;
TCalc_priestHealingFocus.castCooldown = nil;
TCalc_priestHealingFocus.requirements = nil;
TCalc_priestHealingFocus.talentDescriptions = {};
TCalc_priestHealingFocus.talentDescriptions[0] = "Gives you a 35% chance to avoid interruption caused by damage while casting any healing spell.";
TCalc_priestHealingFocus.talentDescriptions[1] = "Gives you a 70% chance to avoid interruption caused by damage while casting any healing spell.";
TCalc_priestHealingFocus.parentTalent = nil;
TCalc_priestHealingFocus.childTalent = nil;
TCalc_priestHealingFocus.iconPath = "Interface\\Icons\\Spell_holy_healingfocus";

TCalc_priestImprovedRenew = {}
TCalc_priestImprovedRenew.maxPoints = 3;
TCalc_priestImprovedRenew.talentName = "Improved Renew";
TCalc_priestImprovedRenew.resourceCost = nil;
TCalc_priestImprovedRenew.castCooldown = nil;
TCalc_priestImprovedRenew.requirements = nil;
TCalc_priestImprovedRenew.talentDescriptions = {};
TCalc_priestImprovedRenew.talentDescriptions[0] = "Increases the amount healed by your Renew spell by 5%.";
TCalc_priestImprovedRenew.talentDescriptions[1] = "Increases the amount healed by your Renew spell by 10%.";
TCalc_priestImprovedRenew.talentDescriptions[2] = "Increases the amount healed by your Renew spell by 15%.";
TCalc_priestImprovedRenew.parentTalent = nil;
TCalc_priestImprovedRenew.childTalent = nil;
TCalc_priestImprovedRenew.iconPath = "Interface\\Icons\\Spell_holy_renew";

TCalc_priestHolySpecialization = {}
TCalc_priestHolySpecialization.maxPoints = 5;
TCalc_priestHolySpecialization.talentName = "Holy Specialization";
TCalc_priestHolySpecialization.resourceCost = nil;
TCalc_priestHolySpecialization.castCooldown = nil;
TCalc_priestHolySpecialization.requirements = nil;
TCalc_priestHolySpecialization.talentDescriptions = {};
TCalc_priestHolySpecialization.talentDescriptions[0] = "Increases the critical effect chance of your Holy spells by 1%.";
TCalc_priestHolySpecialization.talentDescriptions[1] = "Increases the critical effect chance of your Holy spells by 2%.";
TCalc_priestHolySpecialization.talentDescriptions[2] = "Increases the critical effect chance of your Holy spells by 3%.";
TCalc_priestHolySpecialization.talentDescriptions[3] = "Increases the critical effect chance of your Holy spells by 4%.";
TCalc_priestHolySpecialization.talentDescriptions[4] = "Increases the critical effect chance of your Holy spells by 5%.";
TCalc_priestHolySpecialization.parentTalent = nil;
TCalc_priestHolySpecialization.childTalent = nil;
TCalc_priestHolySpecialization.iconPath = "Interface\\Icons\\Spell_holy_sealofsalvation";

--Tier 1

TCalc_priestSpellWarding = {}
TCalc_priestSpellWarding.maxPoints = 5;
TCalc_priestSpellWarding.talentName = "Spell Warding";
TCalc_priestSpellWarding.resourceCost = nil;
TCalc_priestSpellWarding.castCooldown = nil;
TCalc_priestSpellWarding.requirements = nil;
TCalc_priestSpellWarding.talentDescriptions = {};
TCalc_priestSpellWarding.talentDescriptions[0] = "Reduces all spell damage taken by 2%.";
TCalc_priestSpellWarding.talentDescriptions[1] = "Reduces all spell damage taken by 4%.";
TCalc_priestSpellWarding.talentDescriptions[2] = "Reduces all spell damage taken by 6%.";
TCalc_priestSpellWarding.talentDescriptions[3] = "Reduces all spell damage taken by 8%.";
TCalc_priestSpellWarding.talentDescriptions[4] = "Reduces all spell damage taken by 10%.";
TCalc_priestSpellWarding.parentTalent = nil;
TCalc_priestSpellWarding.childTalent = nil;
TCalc_priestSpellWarding.iconPath = "Interface\\Icons\\Spell_holy_spellwarding";

TCalc_priestDivineFury = {}
TCalc_priestDivineFury.maxPoints = 5;
TCalc_priestDivineFury.talentName = "Divine Fury";
TCalc_priestDivineFury.resourceCost = nil;
TCalc_priestDivineFury.castCooldown = nil;
TCalc_priestDivineFury.requirements = nil;
TCalc_priestDivineFury.talentDescriptions = {};
TCalc_priestDivineFury.talentDescriptions[0] = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1 sec.";
TCalc_priestDivineFury.talentDescriptions[1] = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2 sec.";
TCalc_priestDivineFury.talentDescriptions[2] = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3 sec.";
TCalc_priestDivineFury.talentDescriptions[3] = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4 sec.";
TCalc_priestDivineFury.talentDescriptions[4] = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5 sec.";
TCalc_priestDivineFury.parentTalent = nil;
TCalc_priestDivineFury.childTalent = TCalc_priestSearingLight;
TCalc_priestDivineFury.iconPath = "Interface\\Icons\\Spell_holy_sealofwrath";

--Tier 2

TCalc_priestHolyNova = {}
TCalc_priestHolyNova.maxPoints = 1;
TCalc_priestHolyNova.talentName = "Holy Nova";
TCalc_priestHolyNova.resourceCost = "185 mana";
TCalc_priestHolyNova.castCooldown = "Instant cast";
TCalc_priestHolyNova.requirements = nil;
TCalc_priestHolyNova.talentDescriptions = {};
TCalc_priestHolyNova.talentDescriptions[0] = "Causes an explosion of holy light around the caster, causing 28 to 33 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 52 to 61. These effects cause no threat.";
TCalc_priestHolyNova.parentTalent = nil;
TCalc_priestHolyNova.childTalent = nil;
TCalc_priestHolyNova.iconPath = "Interface\\Icons\\Spell_holy_holynova";

TCalc_priestBlessedRecovery = {}
TCalc_priestBlessedRecovery.maxPoints = 3;
TCalc_priestBlessedRecovery.talentName = "Blessed Recovery";
TCalc_priestBlessedRecovery.resourceCost = nil;
TCalc_priestBlessedRecovery.castCooldown = nil;
TCalc_priestBlessedRecovery.requirements = nil;
TCalc_priestBlessedRecovery.talentDescriptions = {};
TCalc_priestBlessedRecovery.talentDescriptions[0] = "After being struck by a melee or ranged critical hit, heal 8% of the damage taken over 6 sec.";
TCalc_priestBlessedRecovery.talentDescriptions[1] = "After being struck by a melee or ranged critical hit, heal 16% of the damage taken over 6 sec.";
TCalc_priestBlessedRecovery.talentDescriptions[2] = "After being struck by a melee or ranged critical hit, heal 25% of the damage taken over 6 sec.";
TCalc_priestBlessedRecovery.parentTalent = nil;
TCalc_priestBlessedRecovery.childTalent = nil;
TCalc_priestBlessedRecovery.iconPath = "Interface\\Icons\\Spell_holy_blessedrecovery";

TCalc_priestInspiration = {}
TCalc_priestInspiration.maxPoints = 3;
TCalc_priestInspiration.talentName = "Inspiration";
TCalc_priestInspiration.resourceCost = nil;
TCalc_priestInspiration.castCooldown = "Instant cast";
TCalc_priestInspiration.requirements = nil;
TCalc_priestInspiration.talentDescriptions = {};
TCalc_priestInspiration.talentDescriptions[0] = "Increases your target's armor by 8% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.";
TCalc_priestInspiration.talentDescriptions[1] = "Increases your target's armor by 16% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.";
TCalc_priestInspiration.talentDescriptions[2] = "Increases your target's armor by 25% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.";
TCalc_priestInspiration.parentTalent = nil;
TCalc_priestInspiration.childTalent = nil;
TCalc_priestInspiration.iconPath = "Interface\\Icons\\Spell_holy_layonhands";

--Tier 3

TCalc_priestHolyReach = {}
TCalc_priestHolyReach.maxPoints = 2;
TCalc_priestHolyReach.talentName = "Holy Reach";
TCalc_priestHolyReach.resourceCost = nil;
TCalc_priestHolyReach.castCooldown = nil;
TCalc_priestHolyReach.requirements = nil;
TCalc_priestHolyReach.talentDescriptions = {};
TCalc_priestHolyReach.talentDescriptions[0] = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing and Holy Nova spells by 10%.";
TCalc_priestHolyReach.talentDescriptions[1] = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing and Holy Nova spells by 20%.";
TCalc_priestHolyReach.parentTalent = nil;
TCalc_priestHolyReach.childTalent = nil;
TCalc_priestHolyReach.iconPath = "Interface\\Icons\\Spell_holy_purify";

TCalc_priestImprovedHealing = {}
TCalc_priestImprovedHealing.maxPoints = 3;
TCalc_priestImprovedHealing.talentName = "Improved Healing";
TCalc_priestImprovedHealing.resourceCost = nil;
TCalc_priestImprovedHealing.castCooldown = nil;
TCalc_priestImprovedHealing.requirements = nil;
TCalc_priestImprovedHealing.talentDescriptions = {};
TCalc_priestImprovedHealing.talentDescriptions[0] = "Reduces the Mana cost of your Lesser Heal, Heal, and Greater Heal spells by 5%.";
TCalc_priestImprovedHealing.talentDescriptions[1] = "Reduces the Mana cost of your Lesser Heal, Heal, and Greater Heal spells by 10%.";
TCalc_priestImprovedHealing.talentDescriptions[2] = "Reduces the Mana cost of your Lesser Heal, Heal, and Greater Heal spells by 15%.";
TCalc_priestImprovedHealing.parentTalent = nil;
TCalc_priestImprovedHealing.childTalent = nil;
TCalc_priestImprovedHealing.iconPath = "Interface\\Icons\\Spell_holy_heal02";

TCalc_priestSearingLight = {}
TCalc_priestSearingLight.maxPoints = 2;
TCalc_priestSearingLight.talentName = "Searing Light";
TCalc_priestSearingLight.resourceCost = nil;
TCalc_priestSearingLight.castCooldown = nil;
TCalc_priestSearingLight.requirements = nil;
TCalc_priestSearingLight.talentDescriptions = {};
TCalc_priestSearingLight.talentDescriptions[0] = "Increases the damage of your Smite and Holy Fire spells by 5%.";
TCalc_priestSearingLight.talentDescriptions[1] = "Increases the damage of your Smite and Holy Fire spells by 10%.";
TCalc_priestSearingLight.parentTalent = TCalc_priestDivineFury;
TCalc_priestSearingLight.childTalent = nil;
TCalc_priestSearingLight.iconPath = "Interface\\Icons\\Spell_holy_searinglightpriest";

--Tier 4

TCalc_priestImprovedPrayerOfHealing = {}
TCalc_priestImprovedPrayerOfHealing.maxPoints = 2;
TCalc_priestImprovedPrayerOfHealing.talentName = "Improved Prayer of Healing";
TCalc_priestImprovedPrayerOfHealing.resourceCost = nil;
TCalc_priestImprovedPrayerOfHealing.castCooldown = nil;
TCalc_priestImprovedPrayerOfHealing.requirements = nil;
TCalc_priestImprovedPrayerOfHealing.talentDescriptions = {};
TCalc_priestImprovedPrayerOfHealing.talentDescriptions[0] = "Reduces the Mana cost of your Prayer of Healing spell by 10%.";
TCalc_priestImprovedPrayerOfHealing.talentDescriptions[1] = "Reduces the Mana cost of your Prayer of Healing spell by 20%.";
TCalc_priestImprovedPrayerOfHealing.parentTalent = nil;
TCalc_priestImprovedPrayerOfHealing.childTalent = nil;
TCalc_priestImprovedPrayerOfHealing.iconPath = "Interface\\Icons\\Spell_holy_prayerofhealing02";

TCalc_priestSpiritOfRedemption = {}
TCalc_priestSpiritOfRedemption.maxPoints = 1;
TCalc_priestSpiritOfRedemption.talentName = "Spirit of Redemption";
TCalc_priestSpiritOfRedemption.resourceCost = nil;
TCalc_priestSpiritOfRedemption.castCooldown = nil;
TCalc_priestSpiritOfRedemption.requirements = nil;
TCalc_priestSpiritOfRedemption.talentDescriptions = {};
TCalc_priestSpiritOfRedemption.talentDescriptions[0] = "Upon death, the priest becomes the Spirit of Redemption for 10 sec. The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects. While in this form the priest can cast any healing spell free of cost. When the effect ends, the priest dies.";
TCalc_priestSpiritOfRedemption.parentTalent = nil;
TCalc_priestSpiritOfRedemption.childTalent = TCalc_priestLightwell;
TCalc_priestSpiritOfRedemption.iconPath = "Interface\\Icons\\Inv_enchant_essenceeternallarge";

TCalc_priestSpiritualGuidance = {}
TCalc_priestSpiritualGuidance.maxPoints = 5;
TCalc_priestSpiritualGuidance.talentName = "Spiritual Guidance";
TCalc_priestSpiritualGuidance.resourceCost = nil;
TCalc_priestSpiritualGuidance.castCooldown = nil;
TCalc_priestSpiritualGuidance.requirements = nil;
TCalc_priestSpiritualGuidance.talentDescriptions = {};
TCalc_priestSpiritualGuidance.talentDescriptions[0] = "Increases spell damage and healing by up to 5% of your total Spirit.";
TCalc_priestSpiritualGuidance.talentDescriptions[1] = "Increases spell damage and healing by up to 10% of your total Spirit.";
TCalc_priestSpiritualGuidance.talentDescriptions[2] = "Increases spell damage and healing by up to 15% of your total Spirit.";
TCalc_priestSpiritualGuidance.talentDescriptions[3] = "Increases spell damage and healing by up to 20% of your total Spirit.";
TCalc_priestSpiritualGuidance.talentDescriptions[4] = "Increases spell damage and healing by up to 25% of your total Spirit.";
TCalc_priestSpiritualGuidance.parentTalent = nil;
TCalc_priestSpiritualGuidance.childTalent = nil;
TCalc_priestSpiritualGuidance.iconPath = "Interface\\Icons\\Spell_holy_spiritualguidence";

--Tier 5

TCalc_priestSpiritualHealing = {}
TCalc_priestSpiritualHealing.maxPoints = 5;
TCalc_priestSpiritualHealing.talentName = "Spiritual Healing";
TCalc_priestSpiritualHealing.resourceCost = nil;
TCalc_priestSpiritualHealing.castCooldown = nil;
TCalc_priestSpiritualHealing.requirements = nil;
TCalc_priestSpiritualHealing.talentDescriptions = {};
TCalc_priestSpiritualHealing.talentDescriptions[0] = "Increases the amount healed by your healing spells by 2%.";
TCalc_priestSpiritualHealing.talentDescriptions[1] = "Increases the amount healed by your healing spells by 4%.";
TCalc_priestSpiritualHealing.talentDescriptions[2] = "Increases the amount healed by your healing spells by 6%.";
TCalc_priestSpiritualHealing.talentDescriptions[3] = "Increases the amount healed by your healing spells by 8%.";
TCalc_priestSpiritualHealing.talentDescriptions[4] = "Increases the amount healed by your healing spells by 10%.";
TCalc_priestSpiritualHealing.parentTalent = nil;
TCalc_priestSpiritualHealing.childTalent = nil;
TCalc_priestSpiritualHealing.iconPath = "Interface\\Icons\\Spell_nature_moonglow";

--Tier 6

TCalc_priestLightwell = {}
TCalc_priestLightwell.maxPoints = 1;
TCalc_priestLightwell.talentName = "Lightwell";
TCalc_priestLightwell.resourceCost = "225 mana";
TCalc_priestLightwell.castCooldown = "1.5 sec cast\t10 min cooldown";
TCalc_priestLightwell.requirements = nil;
TCalc_priestLightwell.talentDescriptions = {};
TCalc_priestLightwell.talentDescriptions[0] = "Creates a holy Lightwell near the priest. Members of your raid or party can click the Lightwell to restore 0 health over 10 sec. Being attacked cancels the effect. Lightwell lasts for 0 sec or 5 charges.";
TCalc_priestLightwell.parentTalent = TCalc_priestSpiritOfRedemption;
TCalc_priestLightwell.childTalent = nil;
TCalc_priestLightwell.iconPath = "Interface\\Icons\\Spell_holy_summonlightwell";

--Tab 2
--Tier 0

TCalc_priestSpiritTap = {}
TCalc_priestSpiritTap.maxPoints = 5;
TCalc_priestSpiritTap.talentName = "Spirit Tap";
TCalc_priestSpiritTap.resourceCost = nil;
TCalc_priestSpiritTap.castCooldown = nil;
TCalc_priestSpiritTap.requirements = nil;
TCalc_priestSpiritTap.talentDescriptions = {};
TCalc_priestSpiritTap.talentDescriptions[0] = "Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.";
TCalc_priestSpiritTap.talentDescriptions[1] = "Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.";
TCalc_priestSpiritTap.talentDescriptions[2] = "Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.";
TCalc_priestSpiritTap.talentDescriptions[3] = "Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.";
TCalc_priestSpiritTap.talentDescriptions[4] = "Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.";
TCalc_priestSpiritTap.parentTalent = nil;
TCalc_priestSpiritTap.childTalent = nil;
TCalc_priestSpiritTap.iconPath = "Interface\\Icons\\Spell_shadow_requiem";

TCalc_priestBlackout = {}
TCalc_priestBlackout.maxPoints = 5;
TCalc_priestBlackout.talentName = "Blackout";
TCalc_priestBlackout.resourceCost = nil;
TCalc_priestBlackout.castCooldown = nil;
TCalc_priestBlackout.requirements = nil;
TCalc_priestBlackout.talentDescriptions = {};
TCalc_priestBlackout.talentDescriptions[0] = "Gives your Shadow damage spells a 2% chance to stun the target for 3 sec.";
TCalc_priestBlackout.talentDescriptions[1] = "Gives your Shadow damage spells a 4% chance to stun the target for 3 sec.";
TCalc_priestBlackout.talentDescriptions[2] = "Gives your Shadow damage spells a 6% chance to stun the target for 3 sec.";
TCalc_priestBlackout.talentDescriptions[3] = "Gives your Shadow damage spells a 8% chance to stun the target for 3 sec.";
TCalc_priestBlackout.talentDescriptions[4] = "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec.";
TCalc_priestBlackout.parentTalent = nil;
TCalc_priestBlackout.childTalent = nil;
TCalc_priestBlackout.iconPath = "Interface\\Icons\\Spell_shadow_gathershadows";

--Tier 1

TCalc_priestShadowAffinity = {}
TCalc_priestShadowAffinity.maxPoints = 3;
TCalc_priestShadowAffinity.talentName = "Shadow Affinity";
TCalc_priestShadowAffinity.resourceCost = nil;
TCalc_priestShadowAffinity.castCooldown = nil;
TCalc_priestShadowAffinity.requirements = nil;
TCalc_priestShadowAffinity.talentDescriptions = {};
TCalc_priestShadowAffinity.talentDescriptions[0] = "Reduces the threat generated by your Shadow spells by 8%.";
TCalc_priestShadowAffinity.talentDescriptions[1] = "Reduces the threat generated by your Shadow spells by 16%.";
TCalc_priestShadowAffinity.talentDescriptions[2] = "Reduces the threat generated by your Shadow spells by 25%.";
TCalc_priestShadowAffinity.parentTalent = nil;
TCalc_priestShadowAffinity.childTalent = nil;
TCalc_priestShadowAffinity.iconPath = "Interface\\Icons\\Spell_shadow_shadowward";

TCalc_priestImprovedShadowWordPain = {}
TCalc_priestImprovedShadowWordPain.maxPoints = 2;
TCalc_priestImprovedShadowWordPain.talentName = "Improved Shadow Word: Pain";
TCalc_priestImprovedShadowWordPain.resourceCost = nil;
TCalc_priestImprovedShadowWordPain.castCooldown = nil;
TCalc_priestImprovedShadowWordPain.requirements = nil;
TCalc_priestImprovedShadowWordPain.talentDescriptions = {};
TCalc_priestImprovedShadowWordPain.talentDescriptions[0] = "Increases the duration of your Shadow Word: Pain spell by 3 sec.";
TCalc_priestImprovedShadowWordPain.talentDescriptions[1] = "Increases the duration of your Shadow Word: Pain spell by 6 sec.";
TCalc_priestImprovedShadowWordPain.parentTalent = nil;
TCalc_priestImprovedShadowWordPain.childTalent = nil;
TCalc_priestImprovedShadowWordPain.iconPath = "Interface\\Icons\\Spell_shadow_shadowwordpain";

TCalc_priestShadowFocus = {}
TCalc_priestShadowFocus.maxPoints = 5;
TCalc_priestShadowFocus.talentName = "Shadow Focus";
TCalc_priestShadowFocus.resourceCost = nil;
TCalc_priestShadowFocus.castCooldown = nil;
TCalc_priestShadowFocus.requirements = nil;
TCalc_priestShadowFocus.talentDescriptions = {};
TCalc_priestShadowFocus.talentDescriptions[0] = "Reduces your target's chance to resist your Shadow spells by 2%.";
TCalc_priestShadowFocus.talentDescriptions[1] = "Reduces your target's chance to resist your Shadow spells by 4%.";
TCalc_priestShadowFocus.talentDescriptions[2] = "Reduces your target's chance to resist your Shadow spells by 6%.";
TCalc_priestShadowFocus.talentDescriptions[3] = "Reduces your target's chance to resist your Shadow spells by 8%.";
TCalc_priestShadowFocus.talentDescriptions[4] = "Reduces your target's chance to resist your Shadow spells by 10%.";
TCalc_priestShadowFocus.parentTalent = nil;
TCalc_priestShadowFocus.childTalent = nil;
TCalc_priestShadowFocus.iconPath = "Interface\\Icons\\Spell_shadow_burningspirit";

--Tier 2

TCalc_priestImprovedPsychicScream = {}
TCalc_priestImprovedPsychicScream.maxPoints = 2;
TCalc_priestImprovedPsychicScream.talentName = "Improved Psychic Scream";
TCalc_priestImprovedPsychicScream.resourceCost = nil;
TCalc_priestImprovedPsychicScream.castCooldown = nil;
TCalc_priestImprovedPsychicScream.requirements = nil;
TCalc_priestImprovedPsychicScream.talentDescriptions = {};
TCalc_priestImprovedPsychicScream.talentDescriptions[0] = "Reduces the cooldown of your Psychic Scream spell by 2 sec.";
TCalc_priestImprovedPsychicScream.talentDescriptions[1] = "Reduces the cooldown of your Psychic Scream spell by 4 sec.";
TCalc_priestImprovedPsychicScream.parentTalent = nil;
TCalc_priestImprovedPsychicScream.childTalent = TCalc_priestSilence;
TCalc_priestImprovedPsychicScream.iconPath = "Interface\\Icons\\Spell_shadow_psychicscream";

TCalc_priestImprovedMindBlast = {}
TCalc_priestImprovedMindBlast.maxPoints = 5;
TCalc_priestImprovedMindBlast.talentName = "Improved Mind Blast";
TCalc_priestImprovedMindBlast.resourceCost = nil;
TCalc_priestImprovedMindBlast.castCooldown = nil;
TCalc_priestImprovedMindBlast.requirements = nil;
TCalc_priestImprovedMindBlast.talentDescriptions = {};
TCalc_priestImprovedMindBlast.talentDescriptions[0] = "Reduces the cooldown of your Mind Blast spell by 0.5 sec.";
TCalc_priestImprovedMindBlast.talentDescriptions[1] = "Reduces the cooldown of your Mind Blast spell by 1.0 sec.";
TCalc_priestImprovedMindBlast.talentDescriptions[2] = "Reduces the cooldown of your Mind Blast spell by 1.5 sec.";
TCalc_priestImprovedMindBlast.talentDescriptions[3] = "Reduces the cooldown of your Mind Blast spell by 2.0 sec.";
TCalc_priestImprovedMindBlast.talentDescriptions[4] = "Reduces the cooldown of your Mind Blast spell by 2.5 sec.";
TCalc_priestImprovedMindBlast.parentTalent = nil;
TCalc_priestImprovedMindBlast.childTalent = nil;
TCalc_priestImprovedMindBlast.iconPath = "Interface\\Icons\\Spell_shadow_unholyfrenzy";

TCalc_priestMindFlay = {}
TCalc_priestMindFlay.maxPoints = 1;
TCalc_priestMindFlay.talentName = "Mind Flay";
TCalc_priestMindFlay.resourceCost = "45 mana\t20 Yd range";
TCalc_priestMindFlay.castCooldown = "Channeled";
TCalc_priestMindFlay.requirements = nil;
TCalc_priestMindFlay.talentDescriptions = {};
TCalc_priestMindFlay.talentDescriptions[0] = "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%.";
TCalc_priestMindFlay.parentTalent = nil;
TCalc_priestMindFlay.childTalent = nil;
TCalc_priestMindFlay.iconPath = "Interface\\Icons\\Spell_shadow_siphonmana";

--Tier 3

TCalc_priestImprovedFade = {}
TCalc_priestImprovedFade.maxPoints = 2;
TCalc_priestImprovedFade.talentName = "Improved Fade";
TCalc_priestImprovedFade.resourceCost = nil;
TCalc_priestImprovedFade.castCooldown = nil;
TCalc_priestImprovedFade.requirements = nil;
TCalc_priestImprovedFade.talentDescriptions = {};
TCalc_priestImprovedFade.talentDescriptions[0] = "Decreases the cooldown of your Fade ability by 3 sec.";
TCalc_priestImprovedFade.talentDescriptions[1] = "Decreases the cooldown of your Fade ability by 6 sec.";
TCalc_priestImprovedFade.parentTalent = nil;
TCalc_priestImprovedFade.childTalent = nil;
TCalc_priestImprovedFade.iconPath = "Interface\\Icons\\Spell_magic_lesserinvisibilty";

TCalc_priestShadowReach = {}
TCalc_priestShadowReach.maxPoints = 3;
TCalc_priestShadowReach.talentName = "Shadow Reach";
TCalc_priestShadowReach.resourceCost = nil;
TCalc_priestShadowReach.castCooldown = nil;
TCalc_priestShadowReach.requirements = nil;
TCalc_priestShadowReach.talentDescriptions = {};
TCalc_priestShadowReach.talentDescriptions[0] = "Increases the range of your Shadow damage spells by 6%.";
TCalc_priestShadowReach.talentDescriptions[1] = "Increases the range of your Shadow damage spells by 13%.";
TCalc_priestShadowReach.talentDescriptions[2] = "Increases the range of your Shadow damage spells by 20%.";
TCalc_priestShadowReach.parentTalent = nil;
TCalc_priestShadowReach.childTalent = nil;
TCalc_priestShadowReach.iconPath = "Interface\\Icons\\Spell_shadow_chilltouch";

TCalc_priestShadowWeaving = {}
TCalc_priestShadowWeaving.maxPoints = 5;
TCalc_priestShadowWeaving.talentName = "Shadow Weaving";
TCalc_priestShadowWeaving.resourceCost = nil;
TCalc_priestShadowWeaving.castCooldown = nil;
TCalc_priestShadowWeaving.requirements = nil;
TCalc_priestShadowWeaving.talentDescriptions = {};
TCalc_priestShadowWeaving.talentDescriptions[0] = "Your Shadow damage spells have a 20% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 5 times.";
TCalc_priestShadowWeaving.talentDescriptions[1] = "Your Shadow damage spells have a 40% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 5 times.";
TCalc_priestShadowWeaving.talentDescriptions[2] = "Your Shadow damage spells have a 60% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 5 times.";
TCalc_priestShadowWeaving.talentDescriptions[3] = "Your Shadow damage spells have a 80% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 5 times.";
TCalc_priestShadowWeaving.talentDescriptions[4] = "Your Shadow damage spells have a 100% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 5 times.";
TCalc_priestShadowWeaving.parentTalent = nil;
TCalc_priestShadowWeaving.childTalent = nil;
TCalc_priestShadowWeaving.iconPath = "Interface\\Icons\\Spell_shadow_blackplague";

--Tier 4

TCalc_priestSilence = {}
TCalc_priestSilence.maxPoints = 1;
TCalc_priestSilence.talentName = "Silence";
TCalc_priestSilence.resourceCost = "225 mana\t20 Yd range";
TCalc_priestSilence.castCooldown = "Inastant\t45 sec cooldown";
TCalc_priestSilence.requirements = nil;
TCalc_priestSilence.talentDescriptions = {};
TCalc_priestSilence.talentDescriptions[0] = "Silences the target, preventing them from casting spells for 5 sec.";
TCalc_priestSilence.parentTalent = TCalc_priestImprovedPsychicScream;
TCalc_priestSilence.childTalent = nil;
TCalc_priestSilence.iconPath = "Interface\\Icons\\Spell_shadow_impphaseshift";

TCalc_priestVampiricEmbrace = {}
TCalc_priestVampiricEmbrace.maxPoints = 1;
TCalc_priestVampiricEmbrace.talentName = "Vampiric Embrace";
TCalc_priestVampiricEmbrace.resourceCost = "40 mana\t20 Yd range";
TCalc_priestVampiricEmbrace.castCooldown = "Inastant\t10 sec cooldown";
TCalc_priestVampiricEmbrace.requirements = nil;
TCalc_priestVampiricEmbrace.talentDescriptions = {};
TCalc_priestVampiricEmbrace.talentDescriptions[0] = "Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow spell damage you deal for 1 min.";
TCalc_priestVampiricEmbrace.parentTalent = nil;
TCalc_priestVampiricEmbrace.childTalent = TCalc_priestShadowform;
TCalc_priestVampiricEmbrace.childTalent2 = TCalc_priestImprovedVampiricEmbrace;
TCalc_priestVampiricEmbrace.iconPath = "Interface\\Icons\\Spell_shadow_unsummonbuilding";

TCalc_priestImprovedVampiricEmbrace = {}
TCalc_priestImprovedVampiricEmbrace.maxPoints = 2;
TCalc_priestImprovedVampiricEmbrace.talentName = "Improved Vampiric Embrace";
TCalc_priestImprovedVampiricEmbrace.resourceCost = nil;
TCalc_priestImprovedVampiricEmbrace.castCooldown = nil;
TCalc_priestImprovedVampiricEmbrace.requirements = nil;
TCalc_priestImprovedVampiricEmbrace.talentDescriptions = {};
TCalc_priestImprovedVampiricEmbrace.talentDescriptions[0] = "Increases the percentage healed by Vampiric Embrace by an additional 5%.";
TCalc_priestImprovedVampiricEmbrace.talentDescriptions[1] = "Increases the percentage healed by Vampiric Embrace by an additional 10%.";
TCalc_priestImprovedVampiricEmbrace.parentTalent = TCalc_priestVampiricEmbrace;
TCalc_priestImprovedVampiricEmbrace.childTalent = nil;
TCalc_priestImprovedVampiricEmbrace.iconPath = "Interface\\Icons\\Spell_shadow_improvedvampiricembrace";

--Tier 5

TCalc_priestDarkness = {}
TCalc_priestDarkness.maxPoints = 5;
TCalc_priestDarkness.talentName = "Darkness";
TCalc_priestDarkness.resourceCost = nil;
TCalc_priestDarkness.castCooldown = nil;
TCalc_priestDarkness.requirements = nil;
TCalc_priestDarkness.talentDescriptions = {};
TCalc_priestDarkness.talentDescriptions[0] = "Increases your Shadow spell damage by 2%.";
TCalc_priestDarkness.talentDescriptions[1] = "Increases your Shadow spell damage by 4%.";
TCalc_priestDarkness.talentDescriptions[2] = "Increases your Shadow spell damage by 6%.";
TCalc_priestDarkness.talentDescriptions[3] = "Increases your Shadow spell damage by 8%.";
TCalc_priestDarkness.talentDescriptions[4] = "Increases your Shadow spell damage by 10%.";
TCalc_priestDarkness.parentTalent = nil;
TCalc_priestDarkness.childTalent = nil;
TCalc_priestDarkness.iconPath = "Interface\\Icons\\Spell_shadow_twilight";

--Tier 6

TCalc_priestShadowform = {}
TCalc_priestShadowform.maxPoints = 1;
TCalc_priestShadowform.talentName = "Shadowform";
TCalc_priestShadowform.resourceCost = "40% of base mana";
TCalc_priestShadowform.castCooldown = "Instant";
TCalc_priestShadowform.requirements = nil;
TCalc_priestShadowform.talentDescriptions = {};
TCalc_priestShadowform.talentDescriptions[0] = "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%. However, you may not cast Holy spells while in this form.";
TCalc_priestShadowform.parentTalent = TCalc_priestVampiricEmbrace;
TCalc_priestShadowform.childTalent = nil;
TCalc_priestShadowform.iconPath = "Interface\\Icons\\Spell_shadow_shadowform";
