--Affliction

TCalc_warlockSuppression = {}
TCalc_warlockSuppression.maxPoints = 5;
TCalc_warlockSuppression.talentName = "Supression";
TCalc_warlockSuppression.resourceCost = nil;
TCalc_warlockSuppression.castCooldown = nil;
TCalc_warlockSuppression.requirements = nil;
TCalc_warlockSuppression.talentDescriptions = {};
TCalc_warlockSuppression.talentDescriptions[0] = "Reduces the chance for enemies to resist your Affliction spells by 2%.";
TCalc_warlockSuppression.talentDescriptions[1] = "Reduces the chance for enemies to resist your Affliction spells by 4%.";
TCalc_warlockSuppression.talentDescriptions[2] = "Reduces the chance for enemies to resist your Affliction spells by 6%.";
TCalc_warlockSuppression.talentDescriptions[3] = "Reduces the chance for enemies to resist your Affliction spells by 8%.";
TCalc_warlockSuppression.talentDescriptions[4] = "Reduces the chance for enemies to resist your Affliction spells by 10%.";
TCalc_warlockSuppression.parentTalent = nil;
TCalc_warlockSuppression.childTalent = nil;
TCalc_warlockSuppression.iconPath = "Interface\\Icons\\Spell_shadow_unsummonbuilding";

TCalc_warlockImprovedCorruption = {}
TCalc_warlockImprovedCorruption.maxPoints = 5;
TCalc_warlockImprovedCorruption.talentName = "Improved Corruption";
TCalc_warlockImprovedCorruption.resourceCost = nil;
TCalc_warlockImprovedCorruption.castCooldown = nil;
TCalc_warlockImprovedCorruption.requirements = nil;
TCalc_warlockImprovedCorruption.talentDescriptions = {};
TCalc_warlockImprovedCorruption.talentDescriptions[0] = "Reduces the casting time of your Corruption spell by 0.4 sec.";
TCalc_warlockImprovedCorruption.talentDescriptions[1] = "Reduces the casting time of your Corruption spell by 0.8 sec.";
TCalc_warlockImprovedCorruption.talentDescriptions[2] = "Reduces the casting time of your Corruption spell by 1.2 sec.";
TCalc_warlockImprovedCorruption.talentDescriptions[3] = "Reduces the casting time of your Corruption spell by 1.6 sec.";
TCalc_warlockImprovedCorruption.talentDescriptions[4] = "Reduces the casting time of your Corruption spell by 2.0 sec.";
TCalc_warlockImprovedCorruption.parentTalent = nil;
TCalc_warlockImprovedCorruption.childTalent = nil;
TCalc_warlockImprovedCorruption.iconPath = "Interface\\Icons\\Spell_shadow_abominationexplosion";

TCalc_warlockImprovedCurseofWeakness = {}
TCalc_warlockImprovedCurseofWeakness.maxPoints = 3;
TCalc_warlockImprovedCurseofWeakness.talentName = "Improved Curse of Weakness";
TCalc_warlockImprovedCurseofWeakness.resourceCost = nil;
TCalc_warlockImprovedCurseofWeakness.castCooldown = nil;
TCalc_warlockImprovedCurseofWeakness.requirements = nil;
TCalc_warlockImprovedCurseofWeakness.talentDescriptions = {};
TCalc_warlockImprovedCurseofWeakness.talentDescriptions[0] = "Increases the effect of your Curse of Weakness by 6%.";
TCalc_warlockImprovedCurseofWeakness.talentDescriptions[1] = "Increases the effect of your Curse of Weakness by 13%.";
TCalc_warlockImprovedCurseofWeakness.talentDescriptions[2] = "Increases the effect of your Curse of Weakness by 20%.";
TCalc_warlockImprovedCurseofWeakness.parentTalent = nil;
TCalc_warlockImprovedCurseofWeakness.childTalent = nil;
TCalc_warlockImprovedCurseofWeakness.iconPath = "Interface\\Icons\\Spell_shadow_curseofmannoroth";

TCalc_warlockImprovedDrainSoul = {}
TCalc_warlockImprovedDrainSoul.maxPoints = 2;
TCalc_warlockImprovedDrainSoul.talentName = "Improved Drain Soul";
TCalc_warlockImprovedDrainSoul.resourceCost = nil;
TCalc_warlockImprovedDrainSoul.castCooldown = nil;
TCalc_warlockImprovedDrainSoul.requirements = nil;
TCalc_warlockImprovedDrainSoul.talentDescriptions = {};
TCalc_warlockImprovedDrainSoul.talentDescriptions[0] = "Gives you a 50% chance to get a 100% increase to your Mana regeneration for 10 sec if the target is killed by you while you drain its soul. In addition your Mana may continue to regenerate while casting at 50% of normal.";
TCalc_warlockImprovedDrainSoul.talentDescriptions[1] = "Gives you a 100% chance to get a 100% increase to your Mana regeneration for 10 sec if the target is killed by you while you drain its soul. In addition your Mana may continue to regenerate while casting at 50% of normal.";
TCalc_warlockImprovedDrainSoul.parentTalent = nil;
TCalc_warlockImprovedDrainSoul.childTalent = nil;
TCalc_warlockImprovedDrainSoul.iconPath = "Interface\\Icons\\Spell_shadow_haunting";

TCalc_warlockImprovedLifeTap = {}
TCalc_warlockImprovedLifeTap.maxPoints = 2;
TCalc_warlockImprovedLifeTap.talentName = "Improved Life Tap";
TCalc_warlockImprovedLifeTap.resourceCost = nil;
TCalc_warlockImprovedLifeTap.castCooldown = nil;
TCalc_warlockImprovedLifeTap.requirements = nil;
TCalc_warlockImprovedLifeTap.talentDescriptions = {};
TCalc_warlockImprovedLifeTap.talentDescriptions[0] = "Increases the amount of Mana awarded by your Life Tap spell by 10%.";
TCalc_warlockImprovedLifeTap.talentDescriptions[1] = "Increases the amount of Mana awarded by your Life Tap spell by 20%.";
TCalc_warlockImprovedLifeTap.parentTalent = nil;
TCalc_warlockImprovedLifeTap.childTalent = nil;
TCalc_warlockImprovedLifeTap.iconPath = "Interface\\Icons\\Spell_shadow_burningspirit";

TCalc_warlockImprovedDrainLife = {}
TCalc_warlockImprovedDrainLife.maxPoints = 5;
TCalc_warlockImprovedDrainLife.talentName = "Improved Drain Life";
TCalc_warlockImprovedDrainLife.resourceCost = nil;
TCalc_warlockImprovedDrainLife.castCooldown = nil;
TCalc_warlockImprovedDrainLife.requirements = nil;
TCalc_warlockImprovedDrainLife.talentDescriptions = {};
TCalc_warlockImprovedDrainLife.talentDescriptions[0] = "Increases the Health drained by your Drain Life spell by 2%.";
TCalc_warlockImprovedDrainLife.talentDescriptions[1] = "Increases the Health drained by your Drain Life spell by 4%.";
TCalc_warlockImprovedDrainLife.talentDescriptions[2] = "Increases the Health drained by your Drain Life spell by 6%.";
TCalc_warlockImprovedDrainLife.talentDescriptions[3] = "Increases the Health drained by your Drain Life spell by 8%.";
TCalc_warlockImprovedDrainLife.talentDescriptions[4] = "Increases the Health drained by your Drain Life spell by 10%.";
TCalc_warlockImprovedDrainLife.parentTalent = nil;
TCalc_warlockImprovedDrainLife.childTalent = nil;
TCalc_warlockImprovedDrainLife.iconPath = "Interface\\Icons\\Spell_shadow_lifedrain02";

TCalc_warlockImprovedCurseofAgony = {}
TCalc_warlockImprovedCurseofAgony.maxPoints = 3;
TCalc_warlockImprovedCurseofAgony.talentName = "Improved Curse of Agony";
TCalc_warlockImprovedCurseofAgony.resourceCost = nil;
TCalc_warlockImprovedCurseofAgony.castCooldown = nil;
TCalc_warlockImprovedCurseofAgony.requirements = nil;
TCalc_warlockImprovedCurseofAgony.talentDescriptions = {};
TCalc_warlockImprovedCurseofAgony.talentDescriptions[0] = "Increases the damage done by your Curse of Agony by 2%.";
TCalc_warlockImprovedCurseofAgony.talentDescriptions[1] = "Increases the damage done by your Curse of Agony by 4%.";
TCalc_warlockImprovedCurseofAgony.talentDescriptions[2] = "Increases the damage done by your Curse of Agony by 6%.";
TCalc_warlockImprovedCurseofAgony.parentTalent = nil;
TCalc_warlockImprovedCurseofAgony.childTalent = nil;
TCalc_warlockImprovedCurseofAgony.iconPath = "Interface\\Icons\\Spell_shadow_curseofsargeras";

TCalc_warlockFelConcentration = {}
TCalc_warlockFelConcentration.maxPoints = 5;
TCalc_warlockFelConcentration.talentName = "Fel Concentration";
TCalc_warlockFelConcentration.resourceCost = nil;
TCalc_warlockFelConcentration.castCooldown = nil;
TCalc_warlockFelConcentration.requirements = nil;
TCalc_warlockFelConcentration.talentDescriptions = {};
TCalc_warlockFelConcentration.talentDescriptions[0] = "Gives you a 14% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.";
TCalc_warlockFelConcentration.talentDescriptions[1] = "Gives you a 28% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.";
TCalc_warlockFelConcentration.talentDescriptions[2] = "Gives you a 42% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.";
TCalc_warlockFelConcentration.talentDescriptions[3] = "Gives you a 56% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.";
TCalc_warlockFelConcentration.talentDescriptions[4] = "Gives you a 70% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.";
TCalc_warlockFelConcentration.parentTalent = nil;
TCalc_warlockFelConcentration.childTalent = nil;
TCalc_warlockFelConcentration.iconPath = "Interface\\Icons\\Spell_shadow_fingerofdeath";

TCalc_warlockAmplifyCurse = {}
TCalc_warlockAmplifyCurse.maxPoints = 1;
TCalc_warlockAmplifyCurse.talentName = "Amplify Curse";
TCalc_warlockAmplifyCurse.resourceCost = nil;
TCalc_warlockAmplifyCurse.castCooldown = "Instant\t3 min cooldown";
TCalc_warlockAmplifyCurse.requirements = nil;
TCalc_warlockAmplifyCurse.talentDescriptions = {};
TCalc_warlockAmplifyCurse.talentDescriptions[0] = "Increases the effect of your next Curse of Weakness or Curse of Agony by 50%, or your next Curse of Exhaustion by 20%. Lasts 30 sec.";
TCalc_warlockAmplifyCurse.parentTalent = nil;
TCalc_warlockAmplifyCurse.childTalent = TCalc_warlockCurseofExhaustion;
TCalc_warlockAmplifyCurse.iconPath = "Interface\\Icons\\Spell_shadow_carrionswarm";

TCalc_warlockGrimReach = {}
TCalc_warlockGrimReach.maxPoints = 2;
TCalc_warlockGrimReach.talentName = "Grim Reach";
TCalc_warlockGrimReach.resourceCost = nil;
TCalc_warlockGrimReach.castCooldown = nil;
TCalc_warlockGrimReach.requirements = nil;
TCalc_warlockGrimReach.talentDescriptions = {};
TCalc_warlockGrimReach.talentDescriptions[0] = "Increases the range of your Affliction spells by 10%.";
TCalc_warlockGrimReach.talentDescriptions[1] = "Increases the range of your Affliction spells by 20%.";
TCalc_warlockGrimReach.parentTalent = nil;
TCalc_warlockGrimReach.childTalent = nil;
TCalc_warlockGrimReach.iconPath = "Interface\\Icons\\Spell_shadow_callofbone";

TCalc_warlockNightfall = {}
TCalc_warlockNightfall.maxPoints = 2;
TCalc_warlockNightfall.talentName = "Nightfall";
TCalc_warlockNightfall.resourceCost = nil;
TCalc_warlockNightfall.castCooldown = nil;
TCalc_warlockNightfall.requirements = nil;
TCalc_warlockNightfall.talentDescriptions = {};
TCalc_warlockNightfall.talentDescriptions[0] = "Gives your Corruption and Drain Life spells a 2% chance to cause you to enter a Shadow Trance state after damaging the opponent. The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100%.";
TCalc_warlockNightfall.talentDescriptions[1] = "Gives your Corruption and Drain Life spells a 4% chance to cause you to enter a Shadow Trance state after damaging the opponent. The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100%.";
TCalc_warlockNightfall.parentTalent = nil;
TCalc_warlockNightfall.childTalent = nil;
TCalc_warlockNightfall.iconPath = "Interface\\Icons\\Spell_shadow_twilight";

TCalc_warlockImprovedDrainMana = {}
TCalc_warlockImprovedDrainMana.maxPoints = 2;
TCalc_warlockImprovedDrainMana.talentName = "Improved Drain Mana";
TCalc_warlockImprovedDrainMana.resourceCost = nil;
TCalc_warlockImprovedDrainMana.castCooldown = nil;
TCalc_warlockImprovedDrainMana.requirements = nil;
TCalc_warlockImprovedDrainMana.talentDescriptions = {};
TCalc_warlockImprovedDrainMana.talentDescriptions[0] = "Causes 15% of the Mana drained by your Drain Mana spell to damage the opponent.";
TCalc_warlockImprovedDrainMana.talentDescriptions[1] = "Causes 30% of the Mana drained by your Drain Mana spell to damage the opponent.";
TCalc_warlockImprovedDrainMana.parentTalent = nil;
TCalc_warlockImprovedDrainMana.childTalent = nil;
TCalc_warlockImprovedDrainMana.iconPath = "Interface\\Icons\\Spell_shadow_siphonmana";

TCalc_warlockSiphonLife = {}
TCalc_warlockSiphonLife.maxPoints = 1;
TCalc_warlockSiphonLife.talentName = "Siphon Life";
TCalc_warlockSiphonLife.resourceCost = "150 mana\t30 yd range";
TCalc_warlockSiphonLife.castCooldown = "Instant cast";
TCalc_warlockSiphonLife.requirements = nil;
TCalc_warlockSiphonLife.talentDescriptions = {};
TCalc_warlockSiphonLife.talentDescriptions[0] = "Transfers 15 health from the target to the caster every 3 sec. Lasts 30 sec.";
TCalc_warlockSiphonLife.parentTalent = nil;
TCalc_warlockSiphonLife.childTalent = TCalc_warlockShadowMastery;
TCalc_warlockSiphonLife.iconPath = "Interface\\Icons\\Spell_shadow_requiem";

TCalc_warlockCurseofExhaustion = {}
TCalc_warlockCurseofExhaustion.maxPoints = 1;
TCalc_warlockCurseofExhaustion.talentName = "Curse of Exhaustion";
TCalc_warlockCurseofExhaustion.resourceCost = "8% of base mana\t30 yd range";
TCalc_warlockCurseofExhaustion.castCooldown = "Instant cast";
TCalc_warlockCurseofExhaustion.requirements = nil;
TCalc_warlockCurseofExhaustion.talentDescriptions = {};
TCalc_warlockCurseofExhaustion.talentDescriptions[0] = "Reduces the target's movement speed by 10% for 12 sec. Only one Curse per Warlock can be active on any one target.";
TCalc_warlockCurseofExhaustion.parentTalent = TCalc_warlockAmplifyCurse;
TCalc_warlockCurseofExhaustion.childTalent = TCalc_warlockImprovedCurseofExhaustion;
TCalc_warlockCurseofExhaustion.iconPath = "Interface\\Icons\\Spell_shadow_grimward";

TCalc_warlockImprovedCurseofExhaustion = {}
TCalc_warlockImprovedCurseofExhaustion.maxPoints = 4;
TCalc_warlockImprovedCurseofExhaustion.talentName = "Improved Curse of Exhaustion";
TCalc_warlockImprovedCurseofExhaustion.resourceCost = nil;
TCalc_warlockImprovedCurseofExhaustion.castCooldown = nil;
TCalc_warlockImprovedCurseofExhaustion.requirements = nil;
TCalc_warlockImprovedCurseofExhaustion.talentDescriptions = {};
TCalc_warlockImprovedCurseofExhaustion.talentDescriptions[0] = "Increases the speed reduction of your Curse of Exhaustion by 5%.";
TCalc_warlockImprovedCurseofExhaustion.talentDescriptions[1] = "Increases the speed reduction of your Curse of Exhaustion by 10%.";
TCalc_warlockImprovedCurseofExhaustion.talentDescriptions[2] = "Increases the speed reduction of your Curse of Exhaustion by 15%.";
TCalc_warlockImprovedCurseofExhaustion.talentDescriptions[3] = "Increases the speed reduction of your Curse of Exhaustion by 20%.";
TCalc_warlockImprovedCurseofExhaustion.parentTalent = TCalc_warlockCurseofExhaustion;
TCalc_warlockImprovedCurseofExhaustion.childTalent = nil;
TCalc_warlockImprovedCurseofExhaustion.iconPath = "Interface\\Icons\\Spell_shadow_grimward";

TCalc_warlockShadowMastery = {}
TCalc_warlockShadowMastery.maxPoints = 5;
TCalc_warlockShadowMastery.talentName = "Shadow Mastery";
TCalc_warlockShadowMastery.resourceCost = nil;
TCalc_warlockShadowMastery.castCooldown = nil;
TCalc_warlockShadowMastery.requirements = nil;
TCalc_warlockShadowMastery.talentDescriptions = {};
TCalc_warlockShadowMastery.talentDescriptions[0] = "Increases the damage dealt or life drained by your Shadow spells by 2%.";
TCalc_warlockShadowMastery.talentDescriptions[1] = "Increases the damage dealt or life drained by your Shadow spells by 4%.";
TCalc_warlockShadowMastery.talentDescriptions[2] = "Increases the damage dealt or life drained by your Shadow spells by 6%.";
TCalc_warlockShadowMastery.talentDescriptions[3] = "Increases the damage dealt or life drained by your Shadow spells by 8%.";
TCalc_warlockShadowMastery.talentDescriptions[4] = "Increases the damage dealt or life drained by your Shadow spells by 10%.";
TCalc_warlockShadowMastery.parentTalent = TCalc_warlockSiphonLife;
TCalc_warlockShadowMastery.childTalent = nil;
TCalc_warlockShadowMastery.iconPath = "Interface\\Icons\\Spell_shadow_shadetruesight";

TCalc_warlockDarkPact = {}
TCalc_warlockDarkPact.maxPoints = 1;
TCalc_warlockDarkPact.talentName = "Dark Pact";
TCalc_warlockDarkPact.resourceCost = "20 yd range";
TCalc_warlockDarkPact.castCooldown = "Instant";
TCalc_warlockDarkPact.requirements = nil;
TCalc_warlockDarkPact.talentDescriptions = {};
TCalc_warlockDarkPact.talentDescriptions[0] = "Drains 150 of your pet's Mana, returning 100% to you.";
TCalc_warlockDarkPact.parentTalent = nil;
TCalc_warlockDarkPact.childTalent = nil;
TCalc_warlockDarkPact.iconPath = "Interface\\Icons\\Spell_shadow_darkritual";

--demonology

TCalc_warlockImprovedHealthstone = {}
TCalc_warlockImprovedHealthstone.maxPoints = 2;
TCalc_warlockImprovedHealthstone.talentName = "Improved Healthstone";
TCalc_warlockImprovedHealthstone.resourceCost = nil;
TCalc_warlockImprovedHealthstone.castCooldown = nil;
TCalc_warlockImprovedHealthstone.requirements = nil;
TCalc_warlockImprovedHealthstone.talentDescriptions = {};
TCalc_warlockImprovedHealthstone.talentDescriptions[0] = "Increases the amount of Health restored by your Healthstone by 10%.";
TCalc_warlockImprovedHealthstone.talentDescriptions[1] = "Increases the amount of Health restored by your Healthstone by 20%.";
TCalc_warlockImprovedHealthstone.parentTalent = nil;
TCalc_warlockImprovedHealthstone.childTalent = nil;
TCalc_warlockImprovedHealthstone.iconPath = "Interface\\Icons\\Inv_stone_04";

TCalc_warlockImprovedImp = {}
TCalc_warlockImprovedImp.maxPoints = 3;
TCalc_warlockImprovedImp.talentName = "Improved Imp";
TCalc_warlockImprovedImp.resourceCost = nil;
TCalc_warlockImprovedImp.castCooldown = nil;
TCalc_warlockImprovedImp.requirements = nil;
TCalc_warlockImprovedImp.talentDescriptions = {};
TCalc_warlockImprovedImp.talentDescriptions[0] = "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 10%.";
TCalc_warlockImprovedImp.talentDescriptions[1] = "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 20%.";
TCalc_warlockImprovedImp.talentDescriptions[2] = "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 30%.";
TCalc_warlockImprovedImp.parentTalent = nil;
TCalc_warlockImprovedImp.childTalent = nil;
TCalc_warlockImprovedImp.iconPath = "Interface\\Icons\\Spell_shadow_summonimp";

TCalc_warlockDemonicEmbrace = {}
TCalc_warlockDemonicEmbrace.maxPoints = 5;
TCalc_warlockDemonicEmbrace.talentName = "Demonic Embrace";
TCalc_warlockDemonicEmbrace.resourceCost = nil;
TCalc_warlockDemonicEmbrace.castCooldown = nil;
TCalc_warlockDemonicEmbrace.requirements = nil;
TCalc_warlockDemonicEmbrace.talentDescriptions = {};
TCalc_warlockDemonicEmbrace.talentDescriptions[0] = "Increases your total Stamina by 3% but reduces your total Spirit by 1%.";
TCalc_warlockDemonicEmbrace.talentDescriptions[1] = "Increases your total Stamina by 6% but reduces your total Spirit by 2%.";
TCalc_warlockDemonicEmbrace.talentDescriptions[2] = "Increases your total Stamina by 9% but reduces your total Spirit by 3%.";
TCalc_warlockDemonicEmbrace.talentDescriptions[3] = "Increases your total Stamina by 12% but reduces your total Spirit by 4%.";
TCalc_warlockDemonicEmbrace.talentDescriptions[4] = "Increases your total Stamina by 15% but reduces your total Spirit by 5%.";
TCalc_warlockDemonicEmbrace.parentTalent = nil;
TCalc_warlockDemonicEmbrace.childTalent = nil;
TCalc_warlockDemonicEmbrace.iconPath = "Interface\\Icons\\Spell_shadow_metamorphosis";

TCalc_warlockImprovedHealthFunnel = {}
TCalc_warlockImprovedHealthFunnel.maxPoints = 2;
TCalc_warlockImprovedHealthFunnel.talentName = "Improved Health Funnel";
TCalc_warlockImprovedHealthFunnel.resourceCost = nil;
TCalc_warlockImprovedHealthFunnel.castCooldown = nil;
TCalc_warlockImprovedHealthFunnel.requirements = nil;
TCalc_warlockImprovedHealthFunnel.talentDescriptions = {};
TCalc_warlockImprovedHealthFunnel.talentDescriptions[0] = "Increases the amount of Health transferred by your Health Funnel spell by 10%.";
TCalc_warlockImprovedHealthFunnel.talentDescriptions[1] = "Increases the amount of Health transferred by your Health Funnel spell by 20%.";
TCalc_warlockImprovedHealthFunnel.parentTalent = nil;
TCalc_warlockImprovedHealthFunnel.childTalent = nil;
TCalc_warlockImprovedHealthFunnel.iconPath = "Interface\\Icons\\Spell_shadow_lifedrain";

TCalc_warlockImprovedVoidwalker = {}
TCalc_warlockImprovedVoidwalker.maxPoints = 3;
TCalc_warlockImprovedVoidwalker.talentName = "Improved Voidwalker";
TCalc_warlockImprovedVoidwalker.resourceCost = nil;
TCalc_warlockImprovedVoidwalker.castCooldown = nil;
TCalc_warlockImprovedVoidwalker.requirements = nil;
TCalc_warlockImprovedVoidwalker.talentDescriptions = {};
TCalc_warlockImprovedVoidwalker.talentDescriptions[0] = "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 10%.";
TCalc_warlockImprovedVoidwalker.talentDescriptions[1] = "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 20%.";
TCalc_warlockImprovedVoidwalker.talentDescriptions[2] = "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 30%.";
TCalc_warlockImprovedVoidwalker.parentTalent = nil;
TCalc_warlockImprovedVoidwalker.childTalent = nil;
TCalc_warlockImprovedVoidwalker.iconPath = "Interface\\Icons\\Spell_shadow_summonvoidwalker";

TCalc_warlockFelIntellect = {}
TCalc_warlockFelIntellect.maxPoints = 5;
TCalc_warlockFelIntellect.talentName = "Fel Intellect";
TCalc_warlockFelIntellect.resourceCost = nil;
TCalc_warlockFelIntellect.castCooldown = nil;
TCalc_warlockFelIntellect.requirements = nil;
TCalc_warlockFelIntellect.talentDescriptions = {};
TCalc_warlockFelIntellect.talentDescriptions[0] = "Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 3%.";
TCalc_warlockFelIntellect.talentDescriptions[1] = "Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 6%.";
TCalc_warlockFelIntellect.talentDescriptions[2] = "Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 9%.";
TCalc_warlockFelIntellect.talentDescriptions[3] = "Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 12%.";
TCalc_warlockFelIntellect.talentDescriptions[4] = "Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 15%.";
TCalc_warlockFelIntellect.parentTalent = nil;
TCalc_warlockFelIntellect.childTalent = nil;
TCalc_warlockFelIntellect.iconPath = "Interface\\Icons\\Spell_holy_magicalsentry";

TCalc_warlockImprovedSuccubus = {}
TCalc_warlockImprovedSuccubus.maxPoints = 3;
TCalc_warlockImprovedSuccubus.talentName = "Improved Succubus";
TCalc_warlockImprovedSuccubus.resourceCost = nil;
TCalc_warlockImprovedSuccubus.castCooldown = nil;
TCalc_warlockImprovedSuccubus.requirements = nil;
TCalc_warlockImprovedSuccubus.talentDescriptions = {};
TCalc_warlockImprovedSuccubus.talentDescriptions[0] = "Increases the effect of your Succubus' Lash of Pain and Soothing Kiss spells by 10%, and increases the duration of your Succubus' Seduction and Lesser Invisibility spells by 10%.";
TCalc_warlockImprovedSuccubus.talentDescriptions[1] = "Increases the effect of your Succubus' Lash of Pain and Soothing Kiss spells by 20%, and increases the duration of your Succubus' Seduction and Lesser Invisibility spells by 20%.";
TCalc_warlockImprovedSuccubus.talentDescriptions[2] = "Increases the effect of your Succubus' Lash of Pain and Soothing Kiss spells by 30%, and increases the duration of your Succubus' Seduction and Lesser Invisibility spells by 30%.";
TCalc_warlockImprovedSuccubus.parentTalent = nil;
TCalc_warlockImprovedSuccubus.childTalent = nil;
TCalc_warlockImprovedSuccubus.iconPath = "Interface\\Icons\\Spell_shadow_summonsuccubus";

TCalc_warlockFelDomination = {}
TCalc_warlockFelDomination.maxPoints = 1;
TCalc_warlockFelDomination.talentName = "Fel Domination";
TCalc_warlockFelDomination.resourceCost = "Instant\t15 min cooldown";
TCalc_warlockFelDomination.castCooldown = nil;
TCalc_warlockFelDomination.requirements = nil;
TCalc_warlockFelDomination.talentDescriptions = {};
TCalc_warlockFelDomination.talentDescriptions[0] = "Your next Imp, Voidwalker, Succubus, or Felhunter Summon spell has its casting time reduced by 5.5 sec and its Mana cost reduced by 50%.";
TCalc_warlockFelDomination.parentTalent = nil;
TCalc_warlockFelDomination.childTalent = TCalc_warlockMasterSummoner;
TCalc_warlockFelDomination.iconPath = "Interface\\Icons\\Spell_nature_removecurse";

TCalc_warlockFelStamina = {}
TCalc_warlockFelStamina.maxPoints = 5;
TCalc_warlockFelStamina.talentName = "Fel Stamina";
TCalc_warlockFelStamina.resourceCost = nil;
TCalc_warlockFelStamina.castCooldown = nil;
TCalc_warlockFelStamina.requirements = nil;
TCalc_warlockFelStamina.talentDescriptions = {};
TCalc_warlockFelStamina.talentDescriptions[0] = "Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 3%.";
TCalc_warlockFelStamina.talentDescriptions[1] = "Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 6%.";
TCalc_warlockFelStamina.talentDescriptions[2] = "Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 9%.";
TCalc_warlockFelStamina.talentDescriptions[3] = "Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 12%.";
TCalc_warlockFelStamina.talentDescriptions[4] = "Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 15%.";
TCalc_warlockFelStamina.parentTalent = nil;
TCalc_warlockFelStamina.childTalent = nil;
TCalc_warlockFelStamina.iconPath = "Interface\\Icons\\Spell_shadow_antishadow";

TCalc_warlockMasterSummoner = {}
TCalc_warlockMasterSummoner.maxPoints = 2;
TCalc_warlockMasterSummoner.talentName = "Master Summoner";
TCalc_warlockMasterSummoner.resourceCost = nil;
TCalc_warlockMasterSummoner.castCooldown = nil;
TCalc_warlockMasterSummoner.requirements = nil;
TCalc_warlockMasterSummoner.talentDescriptions = {};
TCalc_warlockMasterSummoner.talentDescriptions[0] = "Reduces the casting time of your Imp, Voidwalker, Succubus, and Felhunter Summoning spells by 2 sec and the Mana cost by 20%.";
TCalc_warlockMasterSummoner.talentDescriptions[1] = "Reduces the casting time of your Imp, Voidwalker, Succubus, and Felhunter Summoning spells by 4 sec and the Mana cost by 40%.";
TCalc_warlockMasterSummoner.parentTalent = TCalc_warlockFelDomination;
TCalc_warlockMasterSummoner.childTalent = nil;
TCalc_warlockMasterSummoner.iconPath = "Interface\\Icons\\Spell_shadow_impphaseshift";

TCalc_warlockUnholyPower = {}
TCalc_warlockUnholyPower.maxPoints = 5;
TCalc_warlockUnholyPower.talentName = "Unholy Power";
TCalc_warlockUnholyPower.resourceCost = nil;
TCalc_warlockUnholyPower.castCooldown = nil;
TCalc_warlockUnholyPower.requirements = nil;
TCalc_warlockUnholyPower.talentDescriptions = {};
TCalc_warlockUnholyPower.talentDescriptions[0] = "Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 4%.";
TCalc_warlockUnholyPower.talentDescriptions[1] = "Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 8%.";
TCalc_warlockUnholyPower.talentDescriptions[2] = "Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 12%.";
TCalc_warlockUnholyPower.talentDescriptions[3] = "Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 16%.";
TCalc_warlockUnholyPower.talentDescriptions[4] = "Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 20%.";
TCalc_warlockUnholyPower.parentTalent = nil;
TCalc_warlockUnholyPower.childTalent = TCalc_warlockMasterDemonologist;
TCalc_warlockUnholyPower.iconPath = "Interface\\Icons\\Spell_shadow_shadowworddominate";

TCalc_warlockImprovedEnslaveDemon = {}
TCalc_warlockImprovedEnslaveDemon.maxPoints = 5;
TCalc_warlockImprovedEnslaveDemon.talentName = "Improved Enslave Demon";
TCalc_warlockImprovedEnslaveDemon.resourceCost = nil;
TCalc_warlockImprovedEnslaveDemon.castCooldown = nil;
TCalc_warlockImprovedEnslaveDemon.requirements = nil;
TCalc_warlockImprovedEnslaveDemon.talentDescriptions = {};
TCalc_warlockImprovedEnslaveDemon.talentDescriptions[0] = "Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 2%.";
TCalc_warlockImprovedEnslaveDemon.talentDescriptions[1] = "Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 4%.";
TCalc_warlockImprovedEnslaveDemon.talentDescriptions[2] = "Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 6%.";
TCalc_warlockImprovedEnslaveDemon.talentDescriptions[3] = "Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 8%.";
TCalc_warlockImprovedEnslaveDemon.talentDescriptions[4] = "Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 10%.";
TCalc_warlockImprovedEnslaveDemon.parentTalent = nil;
TCalc_warlockImprovedEnslaveDemon.childTalent = nil;
TCalc_warlockImprovedEnslaveDemon.iconPath = "Interface\\Icons\\Spell_shadow_enslavedemon";

TCalc_warlockDemonicSacrifice = {}
TCalc_warlockDemonicSacrifice.maxPoints = 1;
TCalc_warlockDemonicSacrifice.talentName = "Demonic Sacrifice";
TCalc_warlockDemonicSacrifice.resourceCost = "100 yd range";
TCalc_warlockDemonicSacrifice.castCooldown = "Instant";
TCalc_warlockDemonicSacrifice.requirements = nil;
TCalc_warlockDemonicSacrifice.talentDescriptions = {};
TCalc_warlockDemonicSacrifice.talentDescriptions[0] = "When activated, sacrifices your summoned demon to grant you an effect that lasts 30 min. The effect is canceled if any Demon is summoned.\n\nImp: Increases your Fire damage by 15%.\n\nVoidwalker: Restores 3% of total Health every 4 sec.\n\nSuccubus: Increases your Shadow damage by 15%.\n\nFelhunter: Restores 2% of total Mana every 4 sec.";
TCalc_warlockDemonicSacrifice.parentTalent = nil;
TCalc_warlockDemonicSacrifice.childTalent = TCalc_warlockSoulLink;
TCalc_warlockDemonicSacrifice.iconPath = "Interface\\Icons\\Spell_shadow_psychicscream";

TCalc_warlockImprovedFirestone = {}
TCalc_warlockImprovedFirestone.maxPoints = 2;
TCalc_warlockImprovedFirestone.talentName = "Improved Firestone";
TCalc_warlockImprovedFirestone.resourceCost = nil;
TCalc_warlockImprovedFirestone.castCooldown = nil;
TCalc_warlockImprovedFirestone.requirements = nil;
TCalc_warlockImprovedFirestone.talentDescriptions = {};
TCalc_warlockImprovedFirestone.talentDescriptions[0] = "Increases the bonus Fire damage from Firestones and the Firestone effect by 15%.";
TCalc_warlockImprovedFirestone.talentDescriptions[1] = "Increases the bonus Fire damage from Firestones and the Firestone effect by 30%.";
TCalc_warlockImprovedFirestone.parentTalent = nil;
TCalc_warlockImprovedFirestone.childTalent = nil;
TCalc_warlockImprovedFirestone.iconPath = "Interface\\Icons\\Inv_ammo_firetar";

TCalc_warlockMasterDemonologist = {}
TCalc_warlockMasterDemonologist.maxPoints = 5;
TCalc_warlockMasterDemonologist.talentName = "Master Demonologist";
TCalc_warlockMasterDemonologist.resourceCost = nil;
TCalc_warlockMasterDemonologist.castCooldown = nil;
TCalc_warlockMasterDemonologist.requirements = nil;
TCalc_warlockMasterDemonologist.talentDescriptions = {};
TCalc_warlockMasterDemonologist.talentDescriptions[0] = "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 4%.\n\nVoidwalker - Reduces physical damage taken by 2%.\n\nSuccubus - Increases all damage caused by 2%.\n\nFelhunter - Increases all resistances by .2 per level.";
TCalc_warlockMasterDemonologist.talentDescriptions[1] = "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 8%.\n\nVoidwalker - Reduces physical damage taken by 4%.\n\nSuccubus - Increases all damage caused by 4%.\n\nFelhunter - Increases all resistances by .4 per level.";
TCalc_warlockMasterDemonologist.talentDescriptions[2] = "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 12%.\n\nVoidwalker - Reduces physical damage taken by 6%.\n\nSuccubus - Increases all damage caused by 6%.\n\nFelhunter - Increases all resistances by .6 per level.";
TCalc_warlockMasterDemonologist.talentDescriptions[3] = "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 16%.\n\nVoidwalker - Reduces physical damage taken by 8%.\n\nSuccubus - Increases all damage caused by 8%.\n\nFelhunter - Increases all resistances by .8 per level.";
TCalc_warlockMasterDemonologist.talentDescriptions[4] = "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 20%.\n\nVoidwalker - Reduces physical damage taken by 10%.\n\nSuccubus - Increases all damage caused by 10%.\n\nFelhunter - Increases all resistances by 1 per level.";
TCalc_warlockMasterDemonologist.parentTalent = TCalc_warlockUnholyPower;
TCalc_warlockMasterDemonologist.childTalent = nil;
TCalc_warlockMasterDemonologist.iconPath = "Interface\\Icons\\Spell_shadow_shadowpact";

TCalc_warlockSoulLink = {}
TCalc_warlockSoulLink.maxPoints = 1;
TCalc_warlockSoulLink.talentName = "Soul Link";
TCalc_warlockSoulLink.resourceCost = "20% of base mana\t100 yd range";
TCalc_warlockSoulLink.castCooldown = "Instant cast";
TCalc_warlockSoulLink.requirements = nil;
TCalc_warlockSoulLink.talentDescriptions = {};
TCalc_warlockSoulLink.talentDescriptions[0] = "When active, 30% of all damage taken by the caster is taken by your Imp, Voidwalker, Succubus, or Felhunter demon instead. In addition, both the demon and master will inflict 3% more damage. Lasts as long as the demon is active.";
TCalc_warlockSoulLink.parentTalent = TCalc_warlockDemonicSacrifice;
TCalc_warlockSoulLink.childTalent = nil;
TCalc_warlockSoulLink.iconPath = "Interface\\Icons\\Spell_shadow_gathershadows";

TCalc_warlockImprovedSpellstone = {}
TCalc_warlockImprovedSpellstone.maxPoints = 2;
TCalc_warlockImprovedSpellstone.talentName = "Improved Spellstone";
TCalc_warlockImprovedSpellstone.resourceCost = nil;
TCalc_warlockImprovedSpellstone.castCooldown = nil;           
TCalc_warlockImprovedSpellstone.requirements = nil;
TCalc_warlockImprovedSpellstone.talentDescriptions = {};
TCalc_warlockImprovedSpellstone.talentDescriptions[0] = "Increases the amount of damage absorbed by your Spellstone by 15%.";
TCalc_warlockImprovedSpellstone.talentDescriptions[1] = "Increases the amount of damage absorbed by your Spellstone by 30%.";
TCalc_warlockImprovedSpellstone.parentTalent = nil;
TCalc_warlockImprovedSpellstone.childTalent = nil;
TCalc_warlockImprovedSpellstone.iconPath = "Interface\\Icons\\Inv_misc_gem_sapphire_01";

--destruction

TCalc_warlockImprovedShadowBolt = {}
TCalc_warlockImprovedShadowBolt.maxPoints = 5;
TCalc_warlockImprovedShadowBolt.talentName = "Improved Shadow Bolt";
TCalc_warlockImprovedShadowBolt.resourceCost = nil;
TCalc_warlockImprovedShadowBolt.castCooldown = nil;
TCalc_warlockImprovedShadowBolt.requirements = nil;
TCalc_warlockImprovedShadowBolt.talentDescriptions = {};
TCalc_warlockImprovedShadowBolt.talentDescriptions[0] = "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 4% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.";
TCalc_warlockImprovedShadowBolt.talentDescriptions[1] = "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 8% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.";
TCalc_warlockImprovedShadowBolt.talentDescriptions[2] = "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 12% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.";
TCalc_warlockImprovedShadowBolt.talentDescriptions[3] = "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 16% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.";
TCalc_warlockImprovedShadowBolt.talentDescriptions[4] = "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.";
TCalc_warlockImprovedShadowBolt.parentTalent = nil;
TCalc_warlockImprovedShadowBolt.childTalent = nil;
TCalc_warlockImprovedShadowBolt.iconPath = "Interface\\Icons\\Spell_shadow_shadowbolt";

TCalc_warlockCataclysm = {}
TCalc_warlockCataclysm.maxPoints = 5;
TCalc_warlockCataclysm.talentName = "Cataclysm";
TCalc_warlockCataclysm.resourceCost = nil;
TCalc_warlockCataclysm.castCooldown = nil;
TCalc_warlockCataclysm.requirements = nil;
TCalc_warlockCataclysm.talentDescriptions = {};
TCalc_warlockCataclysm.talentDescriptions[0] = "Reduces the Mana cost of your Destruction spells by 5%.";
TCalc_warlockCataclysm.talentDescriptions[1] = "Reduces the Mana cost of your Destruction spells by 5%.";
TCalc_warlockCataclysm.talentDescriptions[2] = "Reduces the Mana cost of your Destruction spells by 5%.";
TCalc_warlockCataclysm.talentDescriptions[3] = "Reduces the Mana cost of your Destruction spells by 5%.";
TCalc_warlockCataclysm.talentDescriptions[4] = "Reduces the Mana cost of your Destruction spells by 5%.";
TCalc_warlockCataclysm.parentTalent = nil;
TCalc_warlockCataclysm.childTalent = nil;
TCalc_warlockCataclysm.iconPath = "Interface\\Icons\\Spell_fire_windsofwoe";

TCalc_warlockBane = {}
TCalc_warlockBane.maxPoints = 5;
TCalc_warlockBane.talentName = "Bane";
TCalc_warlockBane.resourceCost = nil;
TCalc_warlockBane.castCooldown = nil;
TCalc_warlockBane.requirements = nil;
TCalc_warlockBane.talentDescriptions = {};
TCalc_warlockBane.talentDescriptions[0] = "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.1 sec and your Soul Fire spell by 0.4 sec.";
TCalc_warlockBane.talentDescriptions[1] = "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.2 sec and your Soul Fire spell by 0.8 sec.";
TCalc_warlockBane.talentDescriptions[2] = "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.3 sec and your Soul Fire spell by 1.2 sec.";
TCalc_warlockBane.talentDescriptions[3] = "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.4 sec and your Soul Fire spell by 1.6 sec.";
TCalc_warlockBane.talentDescriptions[4] = "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.5 sec and your Soul Fire spell by 2 sec.";
TCalc_warlockBane.parentTalent = nil;
TCalc_warlockBane.childTalent = nil;
TCalc_warlockBane.iconPath = "Interface\\Icons\\Spell_shadow_deathpact";

TCalc_warlockAftermath = {}
TCalc_warlockAftermath.maxPoints = 5;
TCalc_warlockAftermath.talentName = "Aftermath";
TCalc_warlockAftermath.resourceCost = nil;
TCalc_warlockAftermath.castCooldown = nil;
TCalc_warlockAftermath.requirements = nil;
TCalc_warlockAftermath.talentDescriptions = {};
TCalc_warlockAftermath.talentDescriptions[0] = "Gives your Destruction spells a 2% chance to daze the target for 5 sec.";
TCalc_warlockAftermath.talentDescriptions[1] = "Gives your Destruction spells a 4% chance to daze the target for 5 sec.";
TCalc_warlockAftermath.talentDescriptions[2] = "Gives your Destruction spells a 6% chance to daze the target for 5 sec.";
TCalc_warlockAftermath.talentDescriptions[3] = "Gives your Destruction spells a 8% chance to daze the target for 5 sec.";
TCalc_warlockAftermath.talentDescriptions[4] = "Gives your Destruction spells a 10% chance to daze the target for 5 sec.";
TCalc_warlockAftermath.parentTalent = nil;
TCalc_warlockAftermath.childTalent = nil;
TCalc_warlockAftermath.iconPath = "Interface\\Icons\\Spell_fire_fire";

TCalc_warlockImprovedFirebolt = {}
TCalc_warlockImprovedFirebolt.maxPoints = 2;
TCalc_warlockImprovedFirebolt.talentName = "Improved Firebolt";
TCalc_warlockImprovedFirebolt.resourceCost = nil;
TCalc_warlockImprovedFirebolt.castCooldown = nil;
TCalc_warlockImprovedFirebolt.requirements = nil;
TCalc_warlockImprovedFirebolt.talentDescriptions = {};
TCalc_warlockImprovedFirebolt.talentDescriptions[0] = "Reduces the casting time of your Imp's Firebolt spell by 0.5 sec.";
TCalc_warlockImprovedFirebolt.talentDescriptions[1] = "Reduces the casting time of your Imp's Firebolt spell by 1 sec.";
TCalc_warlockImprovedFirebolt.parentTalent = nil;
TCalc_warlockImprovedFirebolt.childTalent = nil;
TCalc_warlockImprovedFirebolt.iconPath = "Interface\\Icons\\Spell_fire_firebolt";

TCalc_warlockImprovedLashofPain = {}
TCalc_warlockImprovedLashofPain.maxPoints = 2;
TCalc_warlockImprovedLashofPain.talentName = "Improved Lash of Pain";
TCalc_warlockImprovedLashofPain.resourceCost = nil;
TCalc_warlockImprovedLashofPain.castCooldown = nil;
TCalc_warlockImprovedLashofPain.requirements = nil;
TCalc_warlockImprovedLashofPain.talentDescriptions = {};
TCalc_warlockImprovedLashofPain.talentDescriptions[0] = "Reduces the cooldown of your Succubus' Lash of Pain spell by 3 sec.";
TCalc_warlockImprovedLashofPain.talentDescriptions[1] = "Reduces the cooldown of your Succubus' Lash of Pain spell by 6 sec.";
TCalc_warlockImprovedLashofPain.parentTalent = nil;
TCalc_warlockImprovedLashofPain.childTalent = nil;
TCalc_warlockImprovedLashofPain.iconPath = "Interface\\Icons\\Spell_shadow_curse";

TCalc_warlockDevastation = {}
TCalc_warlockDevastation.maxPoints = 5;
TCalc_warlockDevastation.talentName = "Devastation";
TCalc_warlockDevastation.resourceCost = nil;
TCalc_warlockDevastation.castCooldown = nil;
TCalc_warlockDevastation.requirements = nil;
TCalc_warlockDevastation.talentDescriptions = {};
TCalc_warlockDevastation.talentDescriptions[0] = "Increases the critical strike chance of your Destruction spells by 1%.";
TCalc_warlockDevastation.talentDescriptions[1] = "Increases the critical strike chance of your Destruction spells by 2%.";
TCalc_warlockDevastation.talentDescriptions[2] = "Increases the critical strike chance of your Destruction spells by 3%.";
TCalc_warlockDevastation.talentDescriptions[3] = "Increases the critical strike chance of your Destruction spells by 4%.";
TCalc_warlockDevastation.talentDescriptions[4] = "Increases the critical strike chance of your Destruction spells by 5%.";
TCalc_warlockDevastation.parentTalent = nil;
TCalc_warlockDevastation.childTalent = TCalc_warlockRuin;
TCalc_warlockDevastation.iconPath = "Interface\\Icons\\Spell_fire_flameshock";

TCalc_warlockShadowburn = {}
TCalc_warlockShadowburn.maxPoints = 1;
TCalc_warlockShadowburn.talentName = "Shadowburn";
TCalc_warlockShadowburn.resourceCost = "105 mana\t24 Yd range";
TCalc_warlockShadowburn.castCooldown = "Instant cast\t15 sec cooldown";
TCalc_warlockShadowburn.requirements = "Reagents: Soul Shard";
TCalc_warlockShadowburn.talentDescriptions = {};
TCalc_warlockShadowburn.talentDescriptions[0] = "Instantly blasts the target for 87 to 100 Shadow damage. If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard.";
TCalc_warlockShadowburn.parentTalent = nil;
TCalc_warlockShadowburn.childTalent = nil;
TCalc_warlockShadowburn.iconPath = "Interface\\Icons\\Spell_shadow_scourgebuild";

TCalc_warlockIntensity = {}
TCalc_warlockIntensity.maxPoints = 2;
TCalc_warlockIntensity.talentName = "Intensity";
TCalc_warlockIntensity.resourceCost = nil;
TCalc_warlockIntensity.castCooldown = nil;
TCalc_warlockIntensity.requirements = nil;
TCalc_warlockIntensity.talentDescriptions = {};
TCalc_warlockIntensity.talentDescriptions[0] = "Gives you a 35% chance to resist interruption caused by damage while channeling the Rain of Fire, Hellfire or Soul Fire spell.";
TCalc_warlockIntensity.talentDescriptions[1] = "Gives you a 70% chance to resist interruption caused by damage while channeling the Rain of Fire, Hellfire or Soul Fire spell.";
TCalc_warlockIntensity.parentTalent = nil;
TCalc_warlockIntensity.childTalent = TCalc_warlockPyroclasm;
TCalc_warlockIntensity.iconPath = "Interface\\Icons\\Spell_fire_lavaspawn";

TCalc_warlockDestructiveReach = {}
TCalc_warlockDestructiveReach.maxPoints = 2;
TCalc_warlockDestructiveReach.talentName = "Destructive Reach";
TCalc_warlockDestructiveReach.resourceCost = nil;
TCalc_warlockDestructiveReach.castCooldown = nil;
TCalc_warlockDestructiveReach.requirements = nil;
TCalc_warlockDestructiveReach.talentDescriptions = {};
TCalc_warlockDestructiveReach.talentDescriptions[0] = "Increases the range of your Destruction spells by 10%.";
TCalc_warlockDestructiveReach.talentDescriptions[1] = "Increases the range of your Destruction spells by 20%.";
TCalc_warlockDestructiveReach.parentTalent = nil;
TCalc_warlockDestructiveReach.childTalent = nil;
TCalc_warlockDestructiveReach.iconPath = "Interface\\Icons\\Spell_shadow_corpseexplode";

TCalc_warlockImprovedSearingPain = {}
TCalc_warlockImprovedSearingPain.maxPoints = 5;
TCalc_warlockImprovedSearingPain.talentName = "Improved Searing Pain";
TCalc_warlockImprovedSearingPain.resourceCost = nil;
TCalc_warlockImprovedSearingPain.castCooldown = nil;
TCalc_warlockImprovedSearingPain.requirements = nil;
TCalc_warlockImprovedSearingPain.talentDescriptions = {};
TCalc_warlockImprovedSearingPain.talentDescriptions[0] = "Increases the critical strike chance of your Searing Pain spell by 2%.";
TCalc_warlockImprovedSearingPain.talentDescriptions[1] = "Increases the critical strike chance of your Searing Pain spell by 4%.";
TCalc_warlockImprovedSearingPain.talentDescriptions[2] = "Increases the critical strike chance of your Searing Pain spell by 6%.";
TCalc_warlockImprovedSearingPain.talentDescriptions[3] = "Increases the critical strike chance of your Searing Pain spell by 8%.";
TCalc_warlockImprovedSearingPain.talentDescriptions[4] = "Increases the critical strike chance of your Searing Pain spell by 10%.";
TCalc_warlockImprovedSearingPain.parentTalent = nil;
TCalc_warlockImprovedSearingPain.childTalent = nil;
TCalc_warlockImprovedSearingPain.iconPath = "Interface\\Icons\\Spell_fire_soulburn";

TCalc_warlockPyroclasm = {}
TCalc_warlockPyroclasm.maxPoints = 2;
TCalc_warlockPyroclasm.talentName = "Pyroclasm";
TCalc_warlockPyroclasm.resourceCost = nil;
TCalc_warlockPyroclasm.castCooldown = nil;
TCalc_warlockPyroclasm.requirements = nil;
TCalc_warlockPyroclasm.talentDescriptions = {};
TCalc_warlockPyroclasm.talentDescriptions[0] = "Gives your Rain of Fire, Hellfire, and Soul Fire spells a 13% chance to stun the target for 3 sec.";
TCalc_warlockPyroclasm.talentDescriptions[1] = "Gives your Rain of Fire, Hellfire, and Soul Fire spells a 26% chance to stun the target for 3 sec.";
TCalc_warlockPyroclasm.parentTalent = TCalc_warlockIntensity;
TCalc_warlockPyroclasm.childTalent = nil;
TCalc_warlockPyroclasm.iconPath = "Interface\\Icons\\Spell_fire_volcano";

TCalc_warlockImprovedImmolate = {}
TCalc_warlockImprovedImmolate.maxPoints = 5;
TCalc_warlockImprovedImmolate.talentName = "Improved Immolate";
TCalc_warlockImprovedImmolate.resourceCost = nil;
TCalc_warlockImprovedImmolate.castCooldown = nil;
TCalc_warlockImprovedImmolate.requirements = nil;
TCalc_warlockImprovedImmolate.talentDescriptions = {};
TCalc_warlockImprovedImmolate.talentDescriptions[0] = "Increases the initial damage of your Immolate spell by 5%.";
TCalc_warlockImprovedImmolate.talentDescriptions[1] = "Increases the initial damage of your Immolate spell by 10%.";
TCalc_warlockImprovedImmolate.talentDescriptions[2] = "Increases the initial damage of your Immolate spell by 15%.";
TCalc_warlockImprovedImmolate.talentDescriptions[3] = "Increases the initial damage of your Immolate spell by 20%.";
TCalc_warlockImprovedImmolate.talentDescriptions[4] = "Increases the initial damage of your Immolate spell by 25%.";
TCalc_warlockImprovedImmolate.parentTalent = nil;
TCalc_warlockImprovedImmolate.childTalent = TCalc_warlockConflagrate;
TCalc_warlockImprovedImmolate.iconPath = "Interface\\Icons\\Spell_fire_immolation";

TCalc_warlockRuin = {}
TCalc_warlockRuin.maxPoints = 1;
TCalc_warlockRuin.talentName = "Ruin";
TCalc_warlockRuin.resourceCost = nil;
TCalc_warlockRuin.castCooldown = nil;
TCalc_warlockRuin.requirements = nil;
TCalc_warlockRuin.talentDescriptions = {};
TCalc_warlockRuin.talentDescriptions[0] = "Increases the critical strike damage bonus of your Destruction spells by 100%.";
TCalc_warlockRuin.parentTalent = TCalc_warlockDevastation;
TCalc_warlockRuin.childTalent = nil;
TCalc_warlockRuin.iconPath = "Interface\\Icons\\Spell_shadow_shadowwordpain";

TCalc_warlockEmberstorm = {}
TCalc_warlockEmberstorm.maxPoints = 5;
TCalc_warlockEmberstorm.talentName = "Emberstorm";
TCalc_warlockEmberstorm.resourceCost = nil;
TCalc_warlockEmberstorm.castCooldown = nil;
TCalc_warlockEmberstorm.requirements = nil;
TCalc_warlockEmberstorm.talentDescriptions = {};
TCalc_warlockEmberstorm.talentDescriptions[0] = "Increases the damage done by your Fire spells by 2%.";
TCalc_warlockEmberstorm.talentDescriptions[1] = "Increases the damage done by your Fire spells by 4%.";
TCalc_warlockEmberstorm.talentDescriptions[2] = "Increases the damage done by your Fire spells by 6%.";
TCalc_warlockEmberstorm.talentDescriptions[3] = "Increases the damage done by your Fire spells by 8%.";
TCalc_warlockEmberstorm.talentDescriptions[4] = "Increases the damage done by your Fire spells by 10%.";
TCalc_warlockEmberstorm.parentTalent = nil;
TCalc_warlockEmberstorm.childTalent = nil;
TCalc_warlockEmberstorm.iconPath = "Interface\\Icons\\Spell_fire_selfdestruct";

TCalc_warlockConflagrate = {}
TCalc_warlockConflagrate.maxPoints = 1;
TCalc_warlockConflagrate.talentName = "Conflagrate";
TCalc_warlockConflagrate.resourceCost = "165 mana\t30 yd range";
TCalc_warlockConflagrate.castCooldown = "Instant cast\t10 sec cooldown";
TCalc_warlockConflagrate.requirements = nil;
TCalc_warlockConflagrate.talentDescriptions = {};
TCalc_warlockConflagrate.talentDescriptions[0] = "Ignites a target that is already afflicted by Immolate, dealing 240 to 307 Fire damage and consuming the Immolate spell.";
TCalc_warlockConflagrate.parentTalent = TCalc_warlockImprovedImmolate;
TCalc_warlockConflagrate.childTalent = nil;
TCalc_warlockConflagrate.iconPath = "Interface\\Icons\\Spell_fire_fireball";