--Tab 0
--Tier 0
TCalc_warriorImprovedHeroicStrike = {}
TCalc_warriorImprovedHeroicStrike.maxPoints = 3;
TCalc_warriorImprovedHeroicStrike.talentName = "Improved Heroic Strike";
TCalc_warriorImprovedHeroicStrike.resourceCost = nil;
TCalc_warriorImprovedHeroicStrike.castCooldown = nil;
TCalc_warriorImprovedHeroicStrike.requirements = nil;
TCalc_warriorImprovedHeroicStrike.talentDescriptions = {};
TCalc_warriorImprovedHeroicStrike.talentDescriptions[0] = "Heroic Strike -1 Rage Cost.";
TCalc_warriorImprovedHeroicStrike.talentDescriptions[1] = "Heroic Strike -2 Rage Cost.";
TCalc_warriorImprovedHeroicStrike.talentDescriptions[2] = "Heroic Strike -3 Rage Cost.";
TCalc_warriorImprovedHeroicStrike.parentTalent = nil;
TCalc_warriorImprovedHeroicStrike.childTalent = nil;
TCalc_warriorImprovedHeroicStrike.iconPath = "Interface\\Icons\\Ability_Rogue_Ambush";

TCalc_warriorDeflection = {}
TCalc_warriorDeflection.maxPoints = 5;
TCalc_warriorDeflection.talentName = "Deflection";
TCalc_warriorDeflection.resourceCost = nil;
TCalc_warriorDeflection.castCooldown = nil;
TCalc_warriorDeflection.requirements = nil;
TCalc_warriorDeflection.talentDescriptions = {};
TCalc_warriorDeflection.talentDescriptions[0] = "Parry +1%.";
TCalc_warriorDeflection.talentDescriptions[1] = "Parry +2%.";
TCalc_warriorDeflection.talentDescriptions[2] = "Parry +3%.";
TCalc_warriorDeflection.talentDescriptions[3] = "Parry +4%.";
TCalc_warriorDeflection.talentDescriptions[4] = "Parry +5%.";
TCalc_warriorDeflection.parentTalent = nil;
TCalc_warriorDeflection.childTalent = nil;
TCalc_warriorDeflection.iconPath = "Interface\\Icons\\Ability_parry";

TCalc_warriorImprovedRend = {}
TCalc_warriorImprovedRend.maxPoints = 3;
TCalc_warriorImprovedRend.talentName = "Improved Rend";
TCalc_warriorImprovedRend.resourceCost = nil;
TCalc_warriorImprovedRend.castCooldown = nil;
TCalc_warriorImprovedRend.requirements = nil;
TCalc_warriorImprovedRend.talentDescriptions = {};
TCalc_warriorImprovedRend.talentDescriptions[0] = "Rend dmg +15%.";
TCalc_warriorImprovedRend.talentDescriptions[1] = "Rend dmg +25%.";
TCalc_warriorImprovedRend.talentDescriptions[2] = "Rend dmg +35%.";
TCalc_warriorImprovedRend.parentTalent = nil;
TCalc_warriorImprovedRend.childTalent = TCalc_warriorImprovedDeepWounds;
TCalc_warriorImprovedRend.iconPath = "Interface\\Icons\\Ability_gouge";

--Tier 1
TCalc_warriorImprovedCharge = {}
TCalc_warriorImprovedCharge.maxPoints = 2;
TCalc_warriorImprovedCharge.talentName = "Improved Charge";
TCalc_warriorImprovedCharge.resourceCost = nil;
TCalc_warriorImprovedCharge.castCooldown = nil;
TCalc_warriorImprovedCharge.requirements = nil;
TCalc_warriorImprovedCharge.talentDescriptions = {};
TCalc_warriorImprovedCharge.talentDescriptions[0] = "Charge +3 Rage.";
TCalc_warriorImprovedCharge.talentDescriptions[1] = "Charge +6 Rage.";
TCalc_warriorImprovedCharge.parentTalent = nil;
TCalc_warriorImprovedCharge.childTalent = nil;
TCalc_warriorImprovedCharge.iconPath = "Interface\\Icons\\Ability_warrior_charge";

TCalc_warriorTacticalMastery = {}
TCalc_warriorTacticalMastery.maxPoints = 5;
TCalc_warriorTacticalMastery.talentName = "Tactical Mastery";
TCalc_warriorTacticalMastery.resourceCost = nil;
TCalc_warriorTacticalMastery.castCooldown = nil;
TCalc_warriorTacticalMastery.requirements = nil;
TCalc_warriorTacticalMastery.talentDescriptions = {};
TCalc_warriorTacticalMastery.talentDescriptions[0] = "Save 5 Rage when change stance.";
TCalc_warriorTacticalMastery.talentDescriptions[1] = "Save 10 Rage when change stance.";
TCalc_warriorTacticalMastery.talentDescriptions[2] = "Save 15 Rage when change stance.";
TCalc_warriorTacticalMastery.talentDescriptions[3] = "Save 20 Rage when change stance.";
TCalc_warriorTacticalMastery.talentDescriptions[4] = "Save 25 Rage when change stance.";
TCalc_warriorTacticalMastery.parentTalent = nil;
TCalc_warriorTacticalMastery.childTalent = TCalc_warriorImprovedAngerManagement;
TCalc_warriorTacticalMastery.iconPath = "Interface\\Icons\\Spell_nature_enchantarmor";

TCalc_warriorImprovedThunderClap = {}
TCalc_warriorImprovedThunderClap.maxPoints = 3;
TCalc_warriorImprovedThunderClap.talentName = "Improved Thunder Clap";
TCalc_warriorImprovedThunderClap.resourceCost = nil;
TCalc_warriorImprovedThunderClap.castCooldown = nil;
TCalc_warriorImprovedThunderClap.requirements = nil;
TCalc_warriorImprovedThunderClap.talentDescriptions = {};
TCalc_warriorImprovedThunderClap.talentDescriptions[0] = "Thunder Clap -1 Rage Cost.";
TCalc_warriorImprovedThunderClap.talentDescriptions[1] = "Thunder Clap -2 Rage Cost.";
TCalc_warriorImprovedThunderClap.talentDescriptions[2] = "Thunder Clap -3 Rage Cost.";
TCalc_warriorImprovedThunderClap.parentTalent = nil;
TCalc_warriorImprovedThunderClap.childTalent = nil;
TCalc_warriorImprovedThunderClap.iconPath = "Interface\\Icons\\Spell_nature_thunderclap";

--Tier 2
TCalc_warriorImprovedOverpower = {}
TCalc_warriorImprovedOverpower.maxPoints = 2;
TCalc_warriorImprovedOverpower.talentName = "Improved Overpower";
TCalc_warriorImprovedOverpower.resourceCost = nil;
TCalc_warriorImprovedOverpower.castCooldown = nil;
TCalc_warriorImprovedOverpower.requirements = nil;
TCalc_warriorImprovedOverpower.talentDescriptions = {};
TCalc_warriorImprovedOverpower.talentDescriptions[0] = "Overpower crit chance +25%.";
TCalc_warriorImprovedOverpower.talentDescriptions[1] = "Overpower crit chance +50%.";
TCalc_warriorImprovedOverpower.parentTalent = nil;
TCalc_warriorImprovedOverpower.childTalent = nil;
TCalc_warriorImprovedOverpower.iconPath = "Interface\\Icons\\Inv_sword_05";

TCalc_warriorAngerManagement = {}
TCalc_warriorAngerManagement.maxPoints = 1;
TCalc_warriorAngerManagement.talentName = "Anger Management";
TCalc_warriorAngerManagement.resourceCost = nil;
TCalc_warriorAngerManagement.castCooldown = nil;
TCalc_warriorAngerManagement.requirements = nil;
TCalc_warriorAngerManagement.talentDescriptions = {};
TCalc_warriorAngerManagement.talentDescriptions[0] = "Increases the time required for your rage to decay while out of combat by 30%.";
TCalc_warriorAngerManagement.parentTalent = TCalc_warriorTacticalMastery;
TCalc_warriorAngerManagement.childTalent = nil;
TCalc_warriorAngerManagement.iconPath = "Interface\\Icons\\Spell_holy_blessingofstamina";

TCalc_warriorDeepWounds = {}
TCalc_warriorDeepWounds.maxPoints = 3;
TCalc_warriorDeepWounds.talentName = "Deep Wounds";
TCalc_warriorDeepWounds.resourceCost = nil;
TCalc_warriorDeepWounds.castCooldown = nil;
TCalc_warriorDeepWounds.requirements = nil;
TCalc_warriorDeepWounds.talentDescriptions = {};
TCalc_warriorDeepWounds.talentDescriptions[0] = "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.";
TCalc_warriorDeepWounds.talentDescriptions[1] = "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.";
TCalc_warriorDeepWounds.talentDescriptions[2] = "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec.";
TCalc_warriorDeepWounds.parentTalent = TCalc_warriorImprovedRend;
TCalc_warriorDeepWounds.childTalent = TCalc_warriorImpale;
TCalc_warriorDeepWounds.iconPath = "Interface\\Icons\\Ability_backstab";

--Tier 3
TCalc_warriorTwoHandedWeaponSpecialization = {}
TCalc_warriorTwoHandedWeaponSpecialization.maxPoints = 5;
TCalc_warriorTwoHandedWeaponSpecialization.talentName = "Two-Handed Weapon Specialization";
TCalc_warriorTwoHandedWeaponSpecialization.resourceCost = nil;
TCalc_warriorTwoHandedWeaponSpecialization.castCooldown = nil;
TCalc_warriorTwoHandedWeaponSpecialization.requirements = nil;
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions = {};
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions[0] = "Two-Handed weapons dmg +1%.";
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions[1] = "Two-Handed weapons dmg +2%.";
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions[2] = "Two-Handed weapons dmg +3%.";
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions[3] = "Two-Handed weapons dmg +4%.";
TCalc_warriorTwoHandedWeaponSpecialization.talentDescriptions[4] = "Two-Handed weapons dmg +5%.";
TCalc_warriorTwoHandedWeaponSpecialization.parentTalent = nil;
TCalc_warriorTwoHandedWeaponSpecialization.childTalent = nil;
TCalc_warriorTwoHandedWeaponSpecialization.iconPath = "Interface\\Icons\\Inv_axe_09";

TCalc_warriorImpale = {}
TCalc_warriorImpale.maxPoints = 2;
TCalc_warriorImpale.talentName = "Impale";
TCalc_warriorImpale.resourceCost = nil;
TCalc_warriorImpale.castCooldown = nil;
TCalc_warriorImpale.requirements = nil;
TCalc_warriorImpale.talentDescriptions = {};
TCalc_warriorImpale.talentDescriptions[0] = "Abilities critical strike damage bonus +10%.";
TCalc_warriorImpale.talentDescriptions[1] = "Abilities critical strike damage bonus +20%.";
TCalc_warriorImpale.parentTalent = TCalc_warriorDeepWounds;
TCalc_warriorImpale.childTalent = nil;
TCalc_warriorImpale.iconPath = "Interface\\Icons\\Ability_searingarrow";

--Tier 4
TCalc_warriorAxeSpecialization = {}
TCalc_warriorAxeSpecialization.maxPoints = 5;
TCalc_warriorAxeSpecialization.talentName = "Axe Specialization";
TCalc_warriorAxeSpecialization.resourceCost = nil;
TCalc_warriorAxeSpecialization.castCooldown = nil;
TCalc_warriorAxeSpecialization.requirements = nil;
TCalc_warriorAxeSpecialization.talentDescriptions = {};
TCalc_warriorAxeSpecialization.talentDescriptions[0] = "Crit chance with axes 1%.";
TCalc_warriorAxeSpecialization.talentDescriptions[1] = "Crit chance with axes 2%.";
TCalc_warriorAxeSpecialization.talentDescriptions[2] = "Crit chance with axes 3%.";
TCalc_warriorAxeSpecialization.talentDescriptions[3] = "Crit chance with axes 4%.";
TCalc_warriorAxeSpecialization.talentDescriptions[4] = "Crit chance with axes 5%.";
TCalc_warriorAxeSpecialization.parentTalent = nil;
TCalc_warriorAxeSpecialization.childTalent = nil;
TCalc_warriorAxeSpecialization.iconPath = "Interface\\Icons\\Inv_axe_06";

TCalc_warriorSweepingStrikes = {}
TCalc_warriorSweepingStrikes.maxPoints = 1;
TCalc_warriorSweepingStrikes.talentName = "Sweeping Strikes";
TCalc_warriorSweepingStrikes.resourceCost = "30 Rage";
TCalc_warriorSweepingStrikes.castCooldown = "Instant\t30 sec cooldown";
TCalc_warriorSweepingStrikes.requirements = nil;
TCalc_warriorSweepingStrikes.talentDescriptions = {};
TCalc_warriorSweepingStrikes.talentDescriptions[0] = "Your next 5 melee attacks strike an additional nearby opponent.";
TCalc_warriorSweepingStrikes.parentTalent = nil;
TCalc_warriorSweepingStrikes.childTalent = TCalc_warriorMortalStrike;
TCalc_warriorSweepingStrikes.iconPath = "Interface\\Icons\\Ability_rogue_slicedice";

TCalc_warriorMaceSpecialization = {}
TCalc_warriorMaceSpecialization.maxPoints = 5;
TCalc_warriorMaceSpecialization.talentName = "Mace Specialization";
TCalc_warriorMaceSpecialization.resourceCost = nil;
TCalc_warriorMaceSpecialization.castCooldown = nil;
TCalc_warriorMaceSpecialization.requirements = nil;
TCalc_warriorMaceSpecialization.talentDescriptions = {};
TCalc_warriorMaceSpecialization.talentDescriptions[0] = "1% chance to stun with a mace.";
TCalc_warriorMaceSpecialization.talentDescriptions[1] = "2% chance to stun with a mace.";
TCalc_warriorMaceSpecialization.talentDescriptions[2] = "3% chance to stun with a mace.";
TCalc_warriorMaceSpecialization.talentDescriptions[3] = "4% chance to stun with a mace.";
TCalc_warriorMaceSpecialization.talentDescriptions[4] = "6% chance to stun with a mace.";
TCalc_warriorMaceSpecialization.parentTalent = nil;
TCalc_warriorMaceSpecialization.childTalent = nil;
TCalc_warriorMaceSpecialization.iconPath = "Interface\\Icons\\Inv_mace_01";

TCalc_warriorSwordSpecialization = {}
TCalc_warriorSwordSpecialization.maxPoints = 5;
TCalc_warriorSwordSpecialization.talentName = "Sword Specialization";
TCalc_warriorSwordSpecialization.resourceCost = nil;
TCalc_warriorSwordSpecialization.castCooldown = nil;
TCalc_warriorSwordSpecialization.requirements = nil;
TCalc_warriorSwordSpecialization.talentDescriptions = {};
TCalc_warriorSwordSpecialization.talentDescriptions[0] = "1% chance to get an extra attack on the same target after dealing damage with your Sword.";
TCalc_warriorSwordSpecialization.talentDescriptions[1] = "2% chance to get an extra attack on the same target after dealing damage with your Sword.";
TCalc_warriorSwordSpecialization.talentDescriptions[2] = "3% chance to get an extra attack on the same target after dealing damage with your Sword.";
TCalc_warriorSwordSpecialization.talentDescriptions[3] = "4% chance to get an extra attack on the same target after dealing damage with your Sword.";
TCalc_warriorSwordSpecialization.talentDescriptions[4] = "5% chance to get an extra attack on the same target after dealing damage with your Sword.";
TCalc_warriorSwordSpecialization.parentTalent = nil;
TCalc_warriorSwordSpecialization.childTalent = nil;
TCalc_warriorSwordSpecialization.iconPath = "Interface\\Icons\\Inv_sword_27";

--Tier 5
TCalc_warriorPolearmSpecialization = {}
TCalc_warriorPolearmSpecialization.maxPoints = 5;
TCalc_warriorPolearmSpecialization.talentName = "Polearm Specialization";
TCalc_warriorPolearmSpecialization.resourceCost = nil;
TCalc_warriorPolearmSpecialization.castCooldown = nil;
TCalc_warriorPolearmSpecialization.requirements = nil;
TCalc_warriorPolearmSpecialization.talentDescriptions = {};
TCalc_warriorPolearmSpecialization.talentDescriptions[0] = "Crit chance with Polearm 1%.";
TCalc_warriorPolearmSpecialization.talentDescriptions[1] = "Crit chance with Polearm 2%.";
TCalc_warriorPolearmSpecialization.talentDescriptions[2] = "Crit chance with Polearm 3%.";
TCalc_warriorPolearmSpecialization.talentDescriptions[3] = "Crit chance with Polearm 4%.";
TCalc_warriorPolearmSpecialization.talentDescriptions[4] = "Crit chance with Polearm 5%.";
TCalc_warriorPolearmSpecialization.parentTalent = nil;
TCalc_warriorPolearmSpecialization.childTalent = nil;
TCalc_warriorPolearmSpecialization.iconPath = "Interface\\Icons\\Inv_weapon_halbard_01";

TCalc_warriorImprovedHamstring = {}
TCalc_warriorImprovedHamstring.maxPoints = 3;
TCalc_warriorImprovedHamstring.talentName = "Improved Hamstring";
TCalc_warriorImprovedHamstring.resourceCost = nil;
TCalc_warriorImprovedHamstring.castCooldown = nil;
TCalc_warriorImprovedHamstring.requirements = nil;
TCalc_warriorImprovedHamstring.talentDescriptions = {};
TCalc_warriorImprovedHamstring.talentDescriptions[0] = "Hamstring has a 5% chance to immobilize the target for 5 sec.";
TCalc_warriorImprovedHamstring.talentDescriptions[1] = "Hamstring has a 10% chance to immobilize the target for 5 sec.";
TCalc_warriorImprovedHamstring.talentDescriptions[2] = "Hamstring has a 15% chance to immobilize the target for 5 sec.";
TCalc_warriorImprovedHamstring.parentTalent = nil;
TCalc_warriorImprovedHamstring.childTalent = nil;
TCalc_warriorImprovedHamstring.iconPath = "Interface\\Icons\\Ability_shockwave";

--Tier 6
TCalc_warriorMortalStrike = {}
TCalc_warriorMortalStrike.maxPoints = 1;
TCalc_warriorMortalStrike.talentName = "Mortal Strike";
TCalc_warriorMortalStrike.resourceCost = "30 rage\t5 yd range";
TCalc_warriorMortalStrike.castCooldown = "Instant\t6 sec cooldown";
TCalc_warriorMortalStrike.requirements = "Requires Melee Weapon";
TCalc_warriorMortalStrike.talentDescriptions = {};
TCalc_warriorMortalStrike.talentDescriptions[0] = "Deals weapon damage +85 and wounds the target, reducing any healing by 50% for 10 sec.";
TCalc_warriorMortalStrike.parentTalent = TCalc_warriorSweepingStrikes;
TCalc_warriorMortalStrike.childTalent = nil;
TCalc_warriorMortalStrike.iconPath = "Interface\\Icons\\Ability_warrior_savageblow";

--Tab 1
--Tier 0
TCalc_warriorBoomingVoice = {}
TCalc_warriorBoomingVoice.maxPoints = 5;
TCalc_warriorBoomingVoice.talentName = "Booming Voice";
TCalc_warriorBoomingVoice.resourceCost = nil;
TCalc_warriorBoomingVoice.castCooldown = nil;
TCalc_warriorBoomingVoice.requirements = nil;
TCalc_warriorBoomingVoice.talentDescriptions = {};
TCalc_warriorBoomingVoice.talentDescriptions[0] = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.";
TCalc_warriorBoomingVoice.talentDescriptions[1] = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%.";
TCalc_warriorBoomingVoice.talentDescriptions[2] = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%.";
TCalc_warriorBoomingVoice.talentDescriptions[3] = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%.";
TCalc_warriorBoomingVoice.talentDescriptions[4] = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%.";
TCalc_warriorBoomingVoice.parentTalent = nil;
TCalc_warriorBoomingVoice.childTalent = nil;
TCalc_warriorBoomingVoice.iconPath = "Interface\\Icons\\Spell_nature_purge";

TCalc_warriorCruelty = {}
TCalc_warriorCruelty.maxPoints = 5;
TCalc_warriorCruelty.talentName = "Cruelty";
TCalc_warriorCruelty.resourceCost = nil;
TCalc_warriorCruelty.castCooldown = nil;
TCalc_warriorCruelty.requirements = nil;
TCalc_warriorCruelty.talentDescriptions = {};
TCalc_warriorCruelty.talentDescriptions[0] = "Crit chance +1%.";
TCalc_warriorCruelty.talentDescriptions[1] = "Crit chance +2%.";
TCalc_warriorCruelty.talentDescriptions[2] = "Crit chance +3%.";
TCalc_warriorCruelty.talentDescriptions[3] = "Crit chance +4%.";
TCalc_warriorCruelty.talentDescriptions[4] = "Crit chance +5%.";
TCalc_warriorCruelty.parentTalent = nil;
TCalc_warriorCruelty.childTalent = nil;
TCalc_warriorCruelty.iconPath = "Interface\\Icons\\Ability_rogue_eviscerate";

--Tier 1
TCalc_warriorImprovedDemoralizingShout = {}
TCalc_warriorImprovedDemoralizingShout.maxPoints = 5;
TCalc_warriorImprovedDemoralizingShout.talentName = "Improved Demoralizing Shout";
TCalc_warriorImprovedDemoralizingShout.resourceCost = nil;
TCalc_warriorImprovedDemoralizingShout.castCooldown = nil;
TCalc_warriorImprovedDemoralizingShout.requirements = nil;
TCalc_warriorImprovedDemoralizingShout.talentDescriptions = {};
TCalc_warriorImprovedDemoralizingShout.talentDescriptions[0] = "Increases the melee attack power reduction of your Demoralizing Shout by 8%.";
TCalc_warriorImprovedDemoralizingShout.talentDescriptions[1] = "Increases the melee attack power reduction of your Demoralizing Shout by 16%.";
TCalc_warriorImprovedDemoralizingShout.talentDescriptions[2] = "Increases the melee attack power reduction of your Demoralizing Shout by 24%.";
TCalc_warriorImprovedDemoralizingShout.talentDescriptions[3] = "Increases the melee attack power reduction of your Demoralizing Shout by 32%.";
TCalc_warriorImprovedDemoralizingShout.talentDescriptions[4] = "Increases the melee attack power reduction of your Demoralizing Shout by 40%.";
TCalc_warriorImprovedDemoralizingShout.parentTalent = nil;
TCalc_warriorImprovedDemoralizingShout.childTalent = nil;
TCalc_warriorImprovedDemoralizingShout.iconPath = "Interface\\Icons\\Ability_warrior_warcry";

TCalc_warriorUnbridledWrath = {}
TCalc_warriorUnbridledWrath.maxPoints = 5;
TCalc_warriorUnbridledWrath.talentName = "Unbridled Wrath";
TCalc_warriorUnbridledWrath.resourceCost = nil;
TCalc_warriorUnbridledWrath.castCooldown = nil;
TCalc_warriorUnbridledWrath.requirements = nil;
TCalc_warriorUnbridledWrath.talentDescriptions = {};
TCalc_warriorUnbridledWrath.talentDescriptions[0] = "Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon.";
TCalc_warriorUnbridledWrath.talentDescriptions[1] = "Gives you a 16% chance to generate an additional Rage point when you deal melee damage with a weapon.";
TCalc_warriorUnbridledWrath.talentDescriptions[2] = "Gives you a 24% chance to generate an additional Rage point when you deal melee damage with a weapon.";
TCalc_warriorUnbridledWrath.talentDescriptions[3] = "Gives you a 32% chance to generate an additional Rage point when you deal melee damage with a weapon.";
TCalc_warriorUnbridledWrath.talentDescriptions[4] = "Gives you a 40% chance to generate an additional Rage point when you deal melee damage with a weapon.";
TCalc_warriorUnbridledWrath.parentTalent = nil;
TCalc_warriorUnbridledWrath.childTalent = nil;
TCalc_warriorUnbridledWrath.iconPath = "Interface\\Icons\\Spell_nature_stoneclawtotem";

--Tier 2
TCalc_warriorImprovedCleave = {}
TCalc_warriorImprovedCleave.maxPoints = 3;
TCalc_warriorImprovedCleave.talentName = "Improved Cleave";
TCalc_warriorImprovedCleave.resourceCost = nil;
TCalc_warriorImprovedCleave.castCooldown = nil;
TCalc_warriorImprovedCleave.requirements = nil;
TCalc_warriorImprovedCleave.talentDescriptions = {};
TCalc_warriorImprovedCleave.talentDescriptions[0] = "Increases the bonus damage done by your Cleave ability by 40%.";
TCalc_warriorImprovedCleave.talentDescriptions[1] = "Increases the bonus damage done by your Cleave ability by 80%.";
TCalc_warriorImprovedCleave.talentDescriptions[2] = "Increases the bonus damage done by your Cleave ability by 120%.";
TCalc_warriorImprovedCleave.parentTalent = nil;
TCalc_warriorImprovedCleave.childTalent = nil;
TCalc_warriorImprovedCleave.iconPath = "Interface\\Icons\\Ability_warrior_cleave";

TCalc_warriorPiercingHowl = {}
TCalc_warriorPiercingHowl.maxPoints = 1;
TCalc_warriorPiercingHowl.talentName = "Piercing Howl";
TCalc_warriorPiercingHowl.resourceCost = "10 Rage";
TCalc_warriorPiercingHowl.castCooldown = "Instant";
TCalc_warriorPiercingHowl.requirements = nil;
TCalc_warriorPiercingHowl.talentDescriptions = {};
TCalc_warriorPiercingHowl.talentDescriptions[0] = "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec.";
TCalc_warriorPiercingHowl.parentTalent = nil;
TCalc_warriorPiercingHowl.childTalent = nil;
TCalc_warriorPiercingHowl.iconPath = "Interface\\Icons\\Spell_shadow_deathscream";

TCalc_warriorBloodCraze = {}
TCalc_warriorBloodCraze.maxPoints = 3;
TCalc_warriorBloodCraze.talentName = "Blood Craze";
TCalc_warriorBloodCraze.resourceCost = nil;
TCalc_warriorBloodCraze.castCooldown = nil;
TCalc_warriorBloodCraze.requirements = nil;
TCalc_warriorBloodCraze.talentDescriptions = {};
TCalc_warriorBloodCraze.talentDescriptions[0] = "Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike.";
TCalc_warriorBloodCraze.talentDescriptions[1] = "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.";
TCalc_warriorBloodCraze.talentDescriptions[2] = "Regenerates 3% of your total Health over 6 sec after being the victim of a critical strike.";
TCalc_warriorBloodCraze.parentTalent = nil;
TCalc_warriorBloodCraze.childTalent = nil;
TCalc_warriorBloodCraze.iconPath = "Interface\\Icons\\Spell_shadow_summonimp";

TCalc_warriorImprovedBattleShout = {}
TCalc_warriorImprovedBattleShout.maxPoints = 5;
TCalc_warriorImprovedBattleShout.talentName = "Improved Battle Shout";
TCalc_warriorImprovedBattleShout.resourceCost = nil;
TCalc_warriorImprovedBattleShout.castCooldown = nil;
TCalc_warriorImprovedBattleShout.requirements = nil;
TCalc_warriorImprovedBattleShout.talentDescriptions = {};
TCalc_warriorImprovedBattleShout.talentDescriptions[0] = "Increases the melee attack power bonus of your Battle Shout by 5%.";
TCalc_warriorImprovedBattleShout.talentDescriptions[1] = "Increases the melee attack power bonus of your Battle Shout by 10%.";
TCalc_warriorImprovedBattleShout.talentDescriptions[2] = "Increases the melee attack power bonus of your Battle Shout by 15%.";
TCalc_warriorImprovedBattleShout.talentDescriptions[3] = "Increases the melee attack power bonus of your Battle Shout by 20%.";
TCalc_warriorImprovedBattleShout.talentDescriptions[4] = "Increases the melee attack power bonus of your Battle Shout by 25%.";
TCalc_warriorImprovedBattleShout.parentTalent = nil;
TCalc_warriorImprovedBattleShout.childTalent = nil;
TCalc_warriorImprovedBattleShout.iconPath = "Interface\\Icons\\Ability_warrior_battleshout";

--Tier 3
TCalc_warriorDualWieldSpecialization = {}
TCalc_warriorDualWieldSpecialization.maxPoints = 5;
TCalc_warriorDualWieldSpecialization.talentName = "Dual Wield Specialization";
TCalc_warriorDualWieldSpecialization.resourceCost = nil
TCalc_warriorDualWieldSpecialization.castCooldown = nil;
TCalc_warriorDualWieldSpecialization.requirements = nil;
TCalc_warriorDualWieldSpecialization.talentDescriptions = {};
TCalc_warriorDualWieldSpecialization.talentDescriptions[0] = "Increases the damage done by your offhand weapon by 5%.";
TCalc_warriorDualWieldSpecialization.talentDescriptions[1] = "Increases the damage done by your offhand weapon by 10%.";
TCalc_warriorDualWieldSpecialization.talentDescriptions[2] = "Increases the damage done by your offhand weapon by 15%.";
TCalc_warriorDualWieldSpecialization.talentDescriptions[3] = "Increases the damage done by your offhand weapon by 20%.";
TCalc_warriorDualWieldSpecialization.talentDescriptions[4] = "Increases the damage done by your offhand weapon by 25%.";
TCalc_warriorDualWieldSpecialization.parentTalent = nil;
TCalc_warriorDualWieldSpecialization.childTalent = nil;
TCalc_warriorDualWieldSpecialization.iconPath = "Interface\\Icons\\Ability_dualwield";

TCalc_warriorImprovedExecute = {}
TCalc_warriorImprovedExecute.maxPoints = 2;
TCalc_warriorImprovedExecute.talentName = "Improved Execute";
TCalc_warriorImprovedExecute.resourceCost = nil;
TCalc_warriorImprovedExecute.castCooldown = nil;
TCalc_warriorImprovedExecute.requirements = nil;
TCalc_warriorImprovedExecute.talentDescriptions = {};
TCalc_warriorImprovedExecute.talentDescriptions[0] = "Reduces the Rage cost of your Execute ability by 2.";
TCalc_warriorImprovedExecute.talentDescriptions[1] = "Reduces the Rage cost of your Execute ability by 5.";
TCalc_warriorImprovedExecute.parentTalent = nil;
TCalc_warriorImprovedExecute.childTalent = nil;
TCalc_warriorImprovedExecute.iconPath = "Interface\\Icons\\Inv_sword_48";

TCalc_warriorEnrage = {}
TCalc_warriorEnrage.maxPoints = 5;
TCalc_warriorEnrage.talentName = "Enrage";
TCalc_warriorEnrage.resourceCost = nil;
TCalc_warriorEnrage.castCooldown = nil;
TCalc_warriorEnrage.requirements = nil;
TCalc_warriorEnrage.talentDescriptions = {};
TCalc_warriorEnrage.talentDescriptions[0] = "Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.";
TCalc_warriorEnrage.talentDescriptions[1] = "Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.";
TCalc_warriorEnrage.talentDescriptions[2] = "Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.";
TCalc_warriorEnrage.talentDescriptions[3] = "Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.";
TCalc_warriorEnrage.talentDescriptions[4] = "Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.";
TCalc_warriorEnrage.parentTalent = nil;
TCalc_warriorEnrage.childTalent = TCalc_warriorFlurry;
TCalc_warriorEnrage.iconPath = "Interface\\Icons\\Spell_shadow_unholyfrenzy";

--Tier 4
TCalc_warriorImprovedSlam = {}
TCalc_warriorImprovedSlam.maxPoints = 5;
TCalc_warriorImprovedSlam.talentName = "Improved Slam";
TCalc_warriorImprovedSlam.resourceCost = nil
TCalc_warriorImprovedSlam.castCooldown = nil;
TCalc_warriorImprovedSlam.requirements = nil;
TCalc_warriorImprovedSlam.talentDescriptions = {};
TCalc_warriorImprovedSlam.talentDescriptions[0] = "Decreases the casting time of your Slam ability by 0.1 sec.";
TCalc_warriorImprovedSlam.talentDescriptions[1] = "Decreases the casting time of your Slam ability by 0.2 sec.";
TCalc_warriorImprovedSlam.talentDescriptions[2] = "Decreases the casting time of your Slam ability by 0.3 sec.";
TCalc_warriorImprovedSlam.talentDescriptions[3] = "Decreases the casting time of your Slam ability by 0.4 sec.";
TCalc_warriorImprovedSlam.talentDescriptions[4] = "Decreases the casting time of your Slam ability by 0.5 sec.";
TCalc_warriorImprovedSlam.parentTalent = nil;
TCalc_warriorImprovedSlam.childTalent = nil;
TCalc_warriorImprovedSlam.iconPath = "Interface\\Icons\\Ability_warrior_decisivestrike";

TCalc_warriorDeathWish = {}
TCalc_warriorDeathWish.maxPoints = 1;
TCalc_warriorDeathWish.talentName = "Death Wish";
TCalc_warriorDeathWish.resourceCost = "10 Rage";
TCalc_warriorDeathWish.castCooldown = "Instant 30 min cooldown";
TCalc_warriorDeathWish.requirements = nil;
TCalc_warriorDeathWish.talentDescriptions = {};
TCalc_warriorDeathWish.talentDescriptions[0] = "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%. Lasts 30 sec.";
TCalc_warriorDeathWish.parentTalent = nil;
TCalc_warriorDeathWish.childTalent = TCalc_warriorBloodthirst;
TCalc_warriorDeathWish.iconPath = "Interface\\Icons\\Spell_shadow_deathpact";

TCalc_warriorImprovedIntercept = {}
TCalc_warriorImprovedIntercept.maxPoints = 2;
TCalc_warriorImprovedIntercept.talentName = "Improved Intercept";
TCalc_warriorImprovedIntercept.resourceCost = nil;
TCalc_warriorImprovedIntercept.castCooldown = nil;
TCalc_warriorImprovedIntercept.requirements = nil;
TCalc_warriorImprovedIntercept.talentDescriptions = {};
TCalc_warriorImprovedIntercept.talentDescriptions[0] = "Reduces the cooldown of your Intercept ability by 5 sec.";
TCalc_warriorImprovedIntercept.talentDescriptions[1] = "Reduces the cooldown of your Intercept ability by 10 sec.";
TCalc_warriorImprovedIntercept.parentTalent = nil;
TCalc_warriorImprovedIntercept.childTalent = nil;
TCalc_warriorImprovedIntercept.iconPath = "Interface\\Icons\\Ability_rogue_sprint";

--Tier 5
TCalc_warriorImprovedBerserkerRage = {}
TCalc_warriorImprovedBerserkerRage.maxPoints = 2;
TCalc_warriorImprovedBerserkerRage.talentName = "Improved Berserker Rage";
TCalc_warriorImprovedBerserkerRage.resourceCost = nil
TCalc_warriorImprovedBerserkerRage.castCooldown = nil;
TCalc_warriorImprovedBerserkerRage.requirements = nil;
TCalc_warriorImprovedBerserkerRage.talentDescriptions = {};
TCalc_warriorImprovedBerserkerRage.talentDescriptions[0] = "The Berserker Rage ability will generate 5 rage when used.";
TCalc_warriorImprovedBerserkerRage.talentDescriptions[1] = "The Berserker Rage ability will generate 10 rage when used.";
TCalc_warriorImprovedBerserkerRage.parentTalent = nil;
TCalc_warriorImprovedBerserkerRage.childTalent = nil;
TCalc_warriorImprovedBerserkerRage.iconPath = "Interface\\Icons\\Spell_nature_ancestralguardian";

TCalc_warriorFlurry = {}
TCalc_warriorFlurry.maxPoints = 5;
TCalc_warriorFlurry.talentName = "Flurry";
TCalc_warriorFlurry.resourceCost = nil;
TCalc_warriorFlurry.castCooldown = nil;
TCalc_warriorFlurry.requirements = nil;
TCalc_warriorFlurry.talentDescriptions = {};
TCalc_warriorFlurry.talentDescriptions[0] = "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.";
TCalc_warriorFlurry.talentDescriptions[1] = "Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.";
TCalc_warriorFlurry.talentDescriptions[2] = "Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.";
TCalc_warriorFlurry.talentDescriptions[3] = "Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.";
TCalc_warriorFlurry.talentDescriptions[4] = "Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike.";
TCalc_warriorFlurry.parentTalent = TCalc_warriorEnrage;
TCalc_warriorFlurry.childTalent = nil;
TCalc_warriorFlurry.iconPath = "Interface\\Icons\\Ability_ghoulfrenzy";

--Tier 6
TCalc_warriorBloodthirst = {}
TCalc_warriorBloodthirst.maxPoints = 1;
TCalc_warriorBloodthirst.talentName = "Bloodthirst";
TCalc_warriorBloodthirst.resourceCost = "30 Rage\tMelee Range";
TCalc_warriorBloodthirst.castCooldown = "Instant";
TCalc_warriorBloodthirst.requirements = nil;
TCalc_warriorBloodthirst.talentDescriptions = {};
TCalc_warriorBloodthirst.talentDescriptions[0] = "Instantly attack the target causing damage equal to 45% of your attack power. In addition, the next 5 successful melee attacks will restore 10 health. This effect lasts 8 sec.";
TCalc_warriorBloodthirst.parentTalent = TCalc_warriorDeathWish;
TCalc_warriorBloodthirst.childTalent = nil;
TCalc_warriorBloodthirst.iconPath = "Interface\\Icons\\Spell_nature_bloodlust";

--Tab 2
--Tier 0
TCalc_warriorShieldSpecialization = {}
TCalc_warriorShieldSpecialization.maxPoints = 5;
TCalc_warriorShieldSpecialization.talentName = "Shield Specialization";
TCalc_warriorShieldSpecialization.resourceCost = nil
TCalc_warriorShieldSpecialization.castCooldown = nil;
TCalc_warriorShieldSpecialization.requirements = nil;
TCalc_warriorShieldSpecialization.talentDescriptions = {};
TCalc_warriorShieldSpecialization.talentDescriptions[0] = "Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.";
TCalc_warriorShieldSpecialization.talentDescriptions[1] = "Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.";
TCalc_warriorShieldSpecialization.talentDescriptions[2] = "Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.";
TCalc_warriorShieldSpecialization.talentDescriptions[3] = "Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.";
TCalc_warriorShieldSpecialization.talentDescriptions[4] = "Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs.";
TCalc_warriorShieldSpecialization.parentTalent = nil;
TCalc_warriorShieldSpecialization.childTalent = TCalc_warriorImprovedShieldBlock;
TCalc_warriorShieldSpecialization.iconPath = "Interface\\Icons\\Inv_shield_06";

TCalc_warriorAnticipation = {}
TCalc_warriorAnticipation.maxPoints = 5;
TCalc_warriorAnticipation.talentName = "Anticipation";
TCalc_warriorAnticipation.resourceCost = nil;
TCalc_warriorAnticipation.castCooldown = nil;
TCalc_warriorAnticipation.requirements = nil;
TCalc_warriorAnticipation.talentDescriptions = {};
TCalc_warriorAnticipation.talentDescriptions[0] = "Increases your Defense skill by 2.";
TCalc_warriorAnticipation.talentDescriptions[1] = "Increases your Defense skill by 4.";
TCalc_warriorAnticipation.talentDescriptions[2] = "Increases your Defense skill by 6.";
TCalc_warriorAnticipation.talentDescriptions[3] = "Increases your Defense skill by 8.";
TCalc_warriorAnticipation.talentDescriptions[4] = "Increases your Defense skill by 10.";
TCalc_warriorAnticipation.parentTalent = nil;
TCalc_warriorAnticipation.childTalent = nil;
TCalc_warriorAnticipation.iconPath = "Interface\\Icons\\Spell_nature_mirrorimage";

--Tier 1
TCalc_warriorImprovedBloodrage = {}
TCalc_warriorImprovedBloodrage.maxPoints = 2;
TCalc_warriorImprovedBloodrage.talentName = "Improved Bloodrage";
TCalc_warriorImprovedBloodrage.resourceCost = nil
TCalc_warriorImprovedBloodrage.castCooldown = nil;
TCalc_warriorImprovedBloodrage.requirements = nil;
TCalc_warriorImprovedBloodrage.talentDescriptions = {};
TCalc_warriorImprovedBloodrage.talentDescriptions[0] = "Increases the instant Rage generated by your Bloodrage ability by 2.";
TCalc_warriorImprovedBloodrage.talentDescriptions[1] = "Increases the instant Rage generated by your Bloodrage ability by 4.";
TCalc_warriorImprovedBloodrage.parentTalent = nil;
TCalc_warriorImprovedBloodrage.childTalent = TCalc_warriorLastStand;
TCalc_warriorImprovedBloodrage.iconPath = "Interface\\Icons\\Ability_racial_bloodrage";

TCalc_warriorToughness = {}
TCalc_warriorToughness.maxPoints = 5;
TCalc_warriorToughness.talentName = "Toughness";
TCalc_warriorToughness.resourceCost = nil;
TCalc_warriorToughness.castCooldown = nil;
TCalc_warriorToughness.requirements = nil;
TCalc_warriorToughness.talentDescriptions = {};
TCalc_warriorToughness.talentDescriptions[0] = "Increases your armor value from items by 2%.";
TCalc_warriorToughness.talentDescriptions[1] = "Increases your armor value from items by 4%.";
TCalc_warriorToughness.talentDescriptions[2] = "Increases your armor value from items by 6%.";
TCalc_warriorToughness.talentDescriptions[3] = "Increases your armor value from items by 8%.";
TCalc_warriorToughness.talentDescriptions[4] = "Increases your armor value from items by 10%.";
TCalc_warriorToughness.parentTalent = nil;
TCalc_warriorToughness.childTalent = nil;
TCalc_warriorToughness.iconPath = "Interface\\Icons\\Spell_holy_devotion";

TCalc_warriorIronWill = {}
TCalc_warriorIronWill.maxPoints = 5;
TCalc_warriorIronWill.talentName = "Iron Will";
TCalc_warriorIronWill.resourceCost = nil;
TCalc_warriorIronWill.castCooldown = nil;
TCalc_warriorIronWill.requirements = nil;
TCalc_warriorIronWill.talentDescriptions = {};
TCalc_warriorIronWill.talentDescriptions[0] = "Increases your chance to resist Stun and Charm effects by an additional 5%.";
TCalc_warriorIronWill.talentDescriptions[1] = "Increases your chance to resist Stun and Charm effects by an additional 10%.";
TCalc_warriorIronWill.talentDescriptions[2] = "Increases your chance to resist Stun and Charm effects by an additional 15%.";
TCalc_warriorIronWill.talentDescriptions[3] = "Increases your chance to resist Stun and Charm effects by an additional 20%.";
TCalc_warriorIronWill.talentDescriptions[4] = "Increases your chance to resist Stun and Charm effects by an additional 25%.";
TCalc_warriorIronWill.parentTalent = nil;
TCalc_warriorIronWill.childTalent = nil;
TCalc_warriorIronWill.iconPath = "Interface\\Icons\\Spell_magic_magearmor";

--Tier 2
TCalc_warriorLastStand = {}
TCalc_warriorLastStand.maxPoints = 1;
TCalc_warriorLastStand.talentName = "Last Stand";
TCalc_warriorLastStand.resourceCost = nil
TCalc_warriorLastStand.castCooldown = nil;
TCalc_warriorLastStand.requirements = nil;
TCalc_warriorLastStand.talentDescriptions = {};
TCalc_warriorLastStand.talentDescriptions[0] = "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds. After the effect expires, the hit points are lost.";
TCalc_warriorLastStand.parentTalent = TCalc_warriorImprovedBloodrage;
TCalc_warriorLastStand.childTalent = nil;
TCalc_warriorLastStand.iconPath = "Interface\\Icons\\Spell_holy_ashestoashes";

TCalc_warriorImprovedShieldBlock = {}
TCalc_warriorImprovedShieldBlock.maxPoints = 3;
TCalc_warriorImprovedShieldBlock.talentName = "Improved Shield Block";
TCalc_warriorImprovedShieldBlock.resourceCost = nil;
TCalc_warriorImprovedShieldBlock.castCooldown = nil;
TCalc_warriorImprovedShieldBlock.requirements = nil;
TCalc_warriorImprovedShieldBlock.talentDescriptions = {};
TCalc_warriorImprovedShieldBlock.talentDescriptions[0] = "Allows your Shield Block ability to block an additional attack and increases the duration by 0.5 second.";
TCalc_warriorImprovedShieldBlock.talentDescriptions[1] = "Allows your Shield Block ability to block an additional attack and increases the duration by 1 second.";
TCalc_warriorImprovedShieldBlock.talentDescriptions[2] = "Allows your Shield Block ability to block an additional attack and increases the duration by 2 second.";
TCalc_warriorImprovedShieldBlock.parentTalent = TCalc_warriorShieldSpecialization;
TCalc_warriorImprovedShieldBlock.childTalent = nil;
TCalc_warriorImprovedShieldBlock.iconPath = "Interface\\Icons\\Ability_defend";

TCalc_warriorImprovedRevenge = {}
TCalc_warriorImprovedRevenge.maxPoints = 3;
TCalc_warriorImprovedRevenge.talentName = "Improved Revenge";
TCalc_warriorImprovedRevenge.resourceCost = nil;
TCalc_warriorImprovedRevenge.castCooldown = nil;
TCalc_warriorImprovedRevenge.requirements = nil;
TCalc_warriorImprovedRevenge.talentDescriptions = {};
TCalc_warriorImprovedRevenge.talentDescriptions[0] = "Gives your Revenge ability a 15% chance to stun the target for 3 sec.";
TCalc_warriorImprovedRevenge.talentDescriptions[1] = "Gives your Revenge ability a 30% chance to stun the target for 3 sec.";
TCalc_warriorImprovedRevenge.talentDescriptions[2] = "Gives your Revenge ability a 45% chance to stun the target for 3 sec.";
TCalc_warriorImprovedRevenge.parentTalent = nil;
TCalc_warriorImprovedRevenge.childTalent = nil;
TCalc_warriorImprovedRevenge.iconPath = "Interface\\Icons\\Ability_warrior_revenge";

TCalc_warriorDefiance = {}
TCalc_warriorDefiance.maxPoints = 5;
TCalc_warriorDefiance.talentName = "Defiance";
TCalc_warriorDefiance.resourceCost = nil;
TCalc_warriorDefiance.castCooldown = nil;
TCalc_warriorDefiance.requirements = nil;
TCalc_warriorDefiance.talentDescriptions = {};
TCalc_warriorDefiance.talentDescriptions[0] = "Increases the threat generated by your attacks by 3% while in Defensive Stance";
TCalc_warriorDefiance.talentDescriptions[1] = "Increases the threat generated by your attacks by 6% while in Defensive Stance.";
TCalc_warriorDefiance.talentDescriptions[2] = "Increases the threat generated by your attacks by 9% while in Defensive Stance.";
TCalc_warriorDefiance.talentDescriptions[3] = "Increases the threat generated by your attacks by 12% while in Defensive Stance.";
TCalc_warriorDefiance.talentDescriptions[4] = "Increases the threat generated by your attacks by 15% while in Defensive Stance.";
TCalc_warriorDefiance.parentTalent = nil;
TCalc_warriorDefiance.childTalent = nil;
TCalc_warriorDefiance.iconPath = "Interface\\Icons\\Ability_warrior_innerrage";

--Tier 3
TCalc_warriorImprovedSunderArmor = {}
TCalc_warriorImprovedSunderArmor.maxPoints = 3;
TCalc_warriorImprovedSunderArmor.talentName = "Improved Sunder Armor";
TCalc_warriorImprovedSunderArmor.resourceCost = nil
TCalc_warriorImprovedSunderArmor.castCooldown = nil;
TCalc_warriorImprovedSunderArmor.requirements = nil;
TCalc_warriorImprovedSunderArmor.talentDescriptions = {};
TCalc_warriorImprovedSunderArmor.talentDescriptions[0] = "Reduces the cost of your Sunder Armor ability by 1 rage point.";
TCalc_warriorImprovedSunderArmor.talentDescriptions[1] = "Reduces the cost of your Sunder Armor ability by 2 rage point.";
TCalc_warriorImprovedSunderArmor.talentDescriptions[2] = "Reduces the cost of your Sunder Armor ability by 3 rage point.";
TCalc_warriorImprovedSunderArmor.parentTalent = nil;
TCalc_warriorImprovedSunderArmor.childTalent = nil;
TCalc_warriorImprovedSunderArmor.iconPath = "Interface\\Icons\\Ability_warrior_sunder";

TCalc_warriorImprovedDisarm = {}
TCalc_warriorImprovedDisarm.maxPoints = 3;
TCalc_warriorImprovedDisarm.talentName = "Improved Disarm";
TCalc_warriorImprovedDisarm.resourceCost = nil;
TCalc_warriorImprovedDisarm.castCooldown = nil;
TCalc_warriorImprovedDisarm.requirements = nil;
TCalc_warriorImprovedDisarm.talentDescriptions = {};
TCalc_warriorImprovedDisarm.talentDescriptions[0] = "Increases the duration of your Disarm ability by 1 secs.";
TCalc_warriorImprovedDisarm.talentDescriptions[1] = "Increases the duration of your Disarm ability by 2 secs.";
TCalc_warriorImprovedDisarm.talentDescriptions[2] = "Increases the duration of your Disarm ability by 3 secs.";
TCalc_warriorImprovedDisarm.parentTalent = nil;
TCalc_warriorImprovedDisarm.childTalent = nil;
TCalc_warriorImprovedDisarm.iconPath = "Interface\\Icons\\Ability_warrior_disarm";

TCalc_warriorImprovedTaunt = {}
TCalc_warriorImprovedTaunt.maxPoints = 2;
TCalc_warriorImprovedTaunt.talentName = "Improved Taunt";
TCalc_warriorImprovedTaunt.resourceCost = nil;
TCalc_warriorImprovedTaunt.castCooldown = nil;
TCalc_warriorImprovedTaunt.requirements = nil;
TCalc_warriorImprovedTaunt.talentDescriptions = {};
TCalc_warriorImprovedTaunt.talentDescriptions[0] = "Reduces the cooldown of your Taunt ability by 1 sec.";
TCalc_warriorImprovedTaunt.talentDescriptions[1] = "Reduces the cooldown of your Taunt ability by 2 sec.";
TCalc_warriorImprovedTaunt.parentTalent = nil;
TCalc_warriorImprovedTaunt.childTalent = nil;
TCalc_warriorImprovedTaunt.iconPath = "Interface\\Icons\\Spell_nature_reincarnation";

--Tier 4
TCalc_warriorImprovedShieldWall = {}
TCalc_warriorImprovedShieldWall.maxPoints = 2;
TCalc_warriorImprovedShieldWall.talentName = "Improved Shield Wall";
TCalc_warriorImprovedShieldWall.resourceCost = nil
TCalc_warriorImprovedShieldWall.castCooldown = nil;
TCalc_warriorImprovedShieldWall.requirements = nil;
TCalc_warriorImprovedShieldWall.talentDescriptions = {};
TCalc_warriorImprovedShieldWall.talentDescriptions[0] = "Increases the effect duration of your Shield Wall ability by 3 secs.";
TCalc_warriorImprovedShieldWall.talentDescriptions[1] = "Increases the effect duration of your Shield Wall ability by 5 secs.";
TCalc_warriorImprovedShieldWall.parentTalent = nil;
TCalc_warriorImprovedShieldWall.childTalent = nil;
TCalc_warriorImprovedShieldWall.iconPath = "Interface\\Icons\\Ability_warrior_shieldwall";

TCalc_warriorConcussionBlow = {}
TCalc_warriorConcussionBlow.maxPoints = 1;
TCalc_warriorConcussionBlow.talentName = "Concussion Blow";
TCalc_warriorConcussionBlow.resourceCost = "15 Rage\tMelee Range";
TCalc_warriorConcussionBlow.castCooldown = "Instant\t45 sec cooldown";
TCalc_warriorConcussionBlow.requirements = nil;
TCalc_warriorConcussionBlow.talentDescriptions = {};
TCalc_warriorConcussionBlow.talentDescriptions[0] = "Stuns the opponent for 5 sec.";
TCalc_warriorConcussionBlow.parentTalent = nil;
TCalc_warriorConcussionBlow.childTalent = TCalc_warriorShieldSlam;
TCalc_warriorConcussionBlow.iconPath = "Interface\\Icons\\Ability_thunderbolt";

TCalc_warriorImprovedShieldBash = {}
TCalc_warriorImprovedShieldBash.maxPoints = 2;
TCalc_warriorImprovedShieldBash.talentName = "Improved Shield Bash";
TCalc_warriorImprovedShieldBash.resourceCost = nil;
TCalc_warriorImprovedShieldBash.castCooldown = nil;
TCalc_warriorImprovedShieldBash.requirements = nil;
TCalc_warriorImprovedShieldBash.talentDescriptions = {};
TCalc_warriorImprovedShieldBash.talentDescriptions[0] = "Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.";
TCalc_warriorImprovedShieldBash.talentDescriptions[1] = "Gives your Shield Bash ability a 100% chance to silence the target for 3 sec.";
TCalc_warriorImprovedShieldBash.parentTalent = nil;
TCalc_warriorImprovedShieldBash.childTalent = nil;
TCalc_warriorImprovedShieldBash.iconPath = "Interface\\Icons\\Ability_warrior_shieldbash";

--Tier 5
TCalc_warriorOneHandedWeaponSpecialization = {}
TCalc_warriorOneHandedWeaponSpecialization.maxPoints = 5;
TCalc_warriorOneHandedWeaponSpecialization.talentName = "One-Handed Weapon Specialization";
TCalc_warriorOneHandedWeaponSpecialization.resourceCost = nil;
TCalc_warriorOneHandedWeaponSpecialization.castCooldown = nil;
TCalc_warriorOneHandedWeaponSpecialization.requirements = nil;
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions = {};
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions[0] = "Increases the damage you deal with One-Handed Melee weapons by 2%.";
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions[1] = "Increases the damage you deal with One-Handed Melee weapons by 4%.";
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions[2] = "Increases the damage you deal with One-Handed Melee weapons by 6%.";
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions[3] = "Increases the damage you deal with One-Handed Melee weapons by 8%.";
TCalc_warriorOneHandedWeaponSpecialization.talentDescriptions[4] = "Increases the damage you deal with One-Handed Melee weapons by 10%.";
TCalc_warriorOneHandedWeaponSpecialization.parentTalent = nil;
TCalc_warriorOneHandedWeaponSpecialization.childTalent = nil;
TCalc_warriorOneHandedWeaponSpecialization.iconPath = "Interface\\Icons\\Inv_sword_20";

--Tier 6
TCalc_warriorShieldSlam = {}
TCalc_warriorShieldSlam.maxPoints = 1;
TCalc_warriorShieldSlam.talentName = "Shield Slam";
TCalc_warriorShieldSlam.resourceCost = "20 rage\tMelee Range";
TCalc_warriorShieldSlam.castCooldown = "Instant\t6 sec cooldown";
TCalc_warriorShieldSlam.requirements = "Requires shield";
TCalc_warriorShieldSlam.talentDescriptions = {};
TCalc_warriorShieldSlam.talentDescriptions[0] = "Slam the target with your shield, causing 225 to 236 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target. Also causes a high amount of threat.";
TCalc_warriorShieldSlam.parentTalent = TCalc_warriorConcussionBlow;
TCalc_warriorShieldSlam.childTalent = nil;
TCalc_warriorShieldSlam.iconPath = "Interface\\Icons\\Inv_shield_05";